# 추가 데이터 수집
- https://www.localdata.go.kr/devcenter/dataDown.do?menuNo=20001
- 서울특별시 데이터 다운로드
- 기준일 : 최초 인허가 ~ 2025-7-31
- 필수 확인 데이터 : 목욕장업, 수영장업, 세탁업
- 추가 확인 데이터 : 미용업, 이용업, 종합체육시설업 등 확인필요

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## 1. 목욕장업 인허가 데이터
 
- 대중목욕탕, 찜질방, 사우나 등 물로 목욕 할 수 있거나 맥반석ㆍ황토 등에게 발생되는 열기 또는 원적외선 등을 이용하여 땀을 낼 수 있는 시설 및 설비 등의 서비스를 제공하는 업소정보
- '6110000_서울특별시_11_44_01_P_목욕장업.csv'

In [328]:
data = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_11_44_01_P_목욕장업.csv', encoding='cp949')
data

,번호,개방서비스명,개방서비스아이디,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,욕실수,발한실여부,조건부허가신고사유,조건부허가시작일자,조건부허가종료일자,건물소유구분명,여성종사자수,남성종사자수,다중이용업소여부,Unnamed: 44
0,1,목욕장업,11_44_01_P,3000000,3000000-202-2019-00001,2019-08-22,NaN,1,영업/정상,1,...,0.0,N,NaN,NaN,NaN,NaN,0.0,0.0,N,NaN
1,2,목욕장업,11_44_01_P,3000000,3000000-202-2024-00001,2024-07-22,NaN,1,영업/정상,1,...,8.0,Y,NaN,NaN,NaN,자가,0.0,0.0,N,NaN
2,3,목욕장업,11_44_01_P,3000000,3000000-202-1970-00392,1970-10-07,NaN,1,영업/정상,1,...,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,4,목욕장업,11_44_01_P,3000000,3000000-202-1963-00410,1963-06-13,NaN,1,영업/정상,1,...,0.0,N,NaN,NaN,NaN,NaN,0.0,0.0,N,NaN
4,5,목욕장업,11_44_01_P,3000000,3000000-202-2003-00009,2003-10-13,NaN,1,영업/정상,1,...,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3945,3946,목욕장업,11_44_01_P,3240000,3240000-202-1988-00234,1988-02-17,NaN,3,폐업,2,...,0.0,N,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3946,3947,목욕장업,11_44_01_P,3240000,3240000-202-1987-00274,1987-12-11,NaN,3,폐업,2,...,0.0,N,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3947,3948,목욕장업,11_44_01_P,3240000,3240000-202-1994-00263,1994-09-16,NaN,3,폐업,2,...,2.0,Y,NaN,NaN,NaN,임대,NaN,NaN,N,NaN
3948,3949,목욕장업,11_44_01_P,3240000,3240000-202-1983-00202,1983-12-22,NaN,3,폐업,2,...,2.0,Y,NaN,NaN,NaN,임대,NaN,NaN,N,NaN
3949,3950,목욕장업,11_44_01_P,3240000,3240000-202-2018-00002,2018-08-16,NaN,3,폐업,2,...,6.0,N,NaN,NaN,NaN,자가,0.0,0.0,N,NaN

In [329]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3950 entries, 0 to 3949
Data columns (total 45 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   번호               3950 non-null   int64
 1   개방서비스명           3950 non-null   object
 2   개방서비스아이디         3950 non-null   object
 3   개방자치단체코드         3950 non-null   int64
 4   관리번호             3950 non-null   object
 5   인허가일자            3950 non-null   object
 6   인허가취소일자          0 non-null      float64
 7   영업상태구분코드         3950 non-null   int64
 8   영업상태명            3950 non-null   object
 9   상세영업상태코드         3950 non-null   int64
 10  상세영업상태명          3950 non-null   object
 11  폐업일자             3285 non-null   object
 12  휴업시작일자           0 non-null      float64
 13  휴업종료일자           0 non-null      float64
 14  재개업일자            0 non-null      float64
 15  소재지전화            3671 non-null   object
 16  소재지면적            3946 non-null   float64
 17  소재지우편번호          3945 non-null   object
 18  소재지전체주소          3945 non-null   object
 19  도로명전체주소          1501 non-null   object
 20  도로명우편번호          1451 non-null   float64
 21  사업장명             3950 non-null   object
 22  최종수정시점           3950 non-null   object
 23  데이터갱신구분          3950 non-null   object
 24  데이터갱신일자          3950 non-null   object
 25  업태구분명            3950 non-null   object
 26  좌표정보x(epsg5174)  3462 non-null   float64
 27  좌표정보y(epsg5174)  3462 non-null   float64
 28  위생업태명            3950 non-null   object
 29  건물지상층수           3016 non-null   float64
 30  건물지하층수           2878 non-null   float64
 31  사용시작지상층          2644 non-null   float64
 32  사용끝지상층           1550 non-null   float64
 33  사용시작지하층          2558 non-null   float64
 34  사용끝지하층           1441 non-null   float64
 35  욕실수              2840 non-null   float64
 36  발한실여부            3949 non-null   object
 37  조건부허가신고사유        5 non-null      object
 38  조건부허가시작일자        3 non-null      float64
 39  조건부허가종료일자        3 non-null      float64
 40  건물소유구분명          833 non-null    object
 41  여성종사자수           663 non-null    float64
 42  남성종사자수           663 non-null    float64
 43  다중이용업소여부         3950 non-null   object
 44  Unnamed: 44      0 non-null      float64
dtypes: float64(20), int64(4), object(21)
memory usage: 1.4+ MB

In [330]:
data.columns

Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', '위생업태명', '건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층',
       '사용시작지하층', '사용끝지하층', '욕실수', '발한실여부', '조건부허가신고사유', '조건부허가시작일자',
       '조건부허가종료일자', '건물소유구분명', '여성종사자수', '남성종사자수', '다중이용업소여부', 'Unnamed: 44'],
      dtype='object')

In [331]:
data['영업상태구분코드'].value_counts()

영업상태구분코드
3    3285
1     665
Name: count, dtype: int64

In [332]:
data['상세영업상태명'].value_counts()

상세영업상태명
폐업    3285
영업     665
Name: count, dtype: int64

In [333]:
data['영업상태명'].value_counts()

영업상태명
폐업       3285
영업/정상     665
Name: count, dtype: int64

In [334]:
data['위생업태명'].value_counts() # 삭제해도 될듯

위생업태명
공동탕업              3187
공동탕업+찜질시설서비스영업     336
목욕장업 기타            168
한증막업               164
찜질시설서비스영업           95
Name: count, dtype: int64

In [335]:
data['업태구분명'].value_counts() # 삭제해도 될듯

업태구분명
공동탕업              3187
공동탕업+찜질시설서비스영업     336
목욕장업 기타            168
한증막업               164
찜질시설서비스영업           95
Name: count, dtype: int64

In [336]:
### 컬럼 제거 ###
# info 정보 기준 널값이 대다수인 경우 + 불필요한 컬럼('위생업태명', '소재지전화', ...)
# 우편번호는 상세주소 있으므로 제거
# 겹치는 정보 제거 : '영업상태구분코드', '상세영업상태코드', '영업상태명'
'''
'번호', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
'영업상태구분코드', '영업상태명', '상세영업상태코드','휴업시작일자', '휴업종료일자',
'재개업일자', '소재지전화', '소재지우편번호', '도로명우편번호',
'최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '위생업태명', 
'건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층','사용시작지하층', '사용끝지하층', 
'조건부허가신고사유', '조건부허가시작일자', '조건부허가종료일자', 
'건물소유구분명', 'Unnamed: 44'
'''




data = data.drop(columns=['번호', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
                          '영업상태구분코드', '영업상태명', '상세영업상태코드','휴업시작일자', '휴업종료일자',
                          '재개업일자', '소재지전화', '소재지우편번호', '도로명우편번호',
                          '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '위생업태명', 
                          '건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층','사용시작지하층', '사용끝지하층', 
                          '조건부허가신고사유', '조건부허가시작일자', '조건부허가종료일자', 
                          '건물소유구분명','Unnamed: 44'], 
                          axis=1)
data.columns

Index(['개방서비스명', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '도로명전체주소', '사업장명',
       '좌표정보x(epsg5174)', '좌표정보y(epsg5174)', '욕실수', '발한실여부', '여성종사자수',
       '남성종사자수', '다중이용업소여부'],
      dtype='object')

In [337]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3950 entries, 0 to 3949
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           3950 non-null   object
 1   상세영업상태명          3950 non-null   object
 2   폐업일자             3285 non-null   object
 3   소재지면적            3946 non-null   float64
 4   소재지전체주소          3945 non-null   object
 5   도로명전체주소          1501 non-null   object
 6   사업장명             3950 non-null   object
 7   좌표정보x(epsg5174)  3462 non-null   float64
 8   좌표정보y(epsg5174)  3462 non-null   float64
 9   욕실수              2840 non-null   float64
 10  발한실여부            3949 non-null   object
 11  여성종사자수           663 non-null    float64
 12  남성종사자수           663 non-null    float64
 13  다중이용업소여부         3950 non-null   object
dtypes: float64(6), object(8)
memory usage: 432.2+ KB

In [338]:
data['폐업일자'] = pd.to_datetime(data['폐업일자'], errors='coerce')

# 폐업일자가 있고 & 2017-01-01 이전인 경우 제거
mask_drop = data['폐업일자'].notna() & (data['폐업일자'] < pd.Timestamp('2017-01-01'))

data = data[~mask_drop]
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1207 entries, 0 to 3949
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           1207 non-null   object
 1   상세영업상태명          1207 non-null   object
 2   폐업일자             542 non-null    datetime64[ns]
 3   소재지면적            1207 non-null   float64
 4   소재지전체주소          1202 non-null   object
 5   도로명전체주소          1205 non-null   object
 6   사업장명             1207 non-null   object
 7   좌표정보x(epsg5174)  1192 non-null   float64
 8   좌표정보y(epsg5174)  1192 non-null   float64
 9   욕실수              1049 non-null   float64
 10  발한실여부            1207 non-null   object
 11  여성종사자수           661 non-null    float64
 12  남성종사자수           661 non-null    float64
 13  다중이용업소여부         1207 non-null   object
dtypes: datetime64[ns](1), float64(6), object(7)
memory usage: 141.4+ KB

In [339]:
### 소재지전체주소, 도로명전체주소 상호보완 ###
# '소재지전체주소'의 NaN 값을 '도로명전체주소' 값으로 채우기
data['소재지전체주소'] = data['소재지전체주소'].fillna(data['도로명전체주소'])

# '도로명전체주소'의 NaN 값을 '소재지전체주소' 값으로 채우기
data['도로명전체주소'] = data['도로명전체주소'].fillna(data['소재지전체주소'])

data.isna().sum()

개방서비스명               0
상세영업상태명              0
폐업일자               665
소재지면적                0
소재지전체주소              0
도로명전체주소              0
사업장명                 0
좌표정보x(epsg5174)     15
좌표정보y(epsg5174)     15
욕실수                158
발한실여부                0
여성종사자수             546
남성종사자수             546
다중이용업소여부             0
dtype: int64

In [340]:
### 소재지전체주소, 도로명전체주소 패턴 파악결과 공백 기준 4번째까지가 건물 주소임, 그 이후는 상세라서 4번째 까지만 인덱싱 ###
# 소재지전체주소
data['소재지전체주소'] = data['소재지전체주소'].str.split().str[:4].str.join(' ')

# 도로명전체주소
data['도로명전체주소'] = data['도로명전체주소'].str.split().str[:4].str.join(' ')

data[['소재지전체주소', '도로명전체주소']]

                     소재지전체주소               도로명전체주소
0      서울특별시 종로구 원남동 49-17번지    서울특별시 종로구 율곡로 180,
1       서울특별시 종로구 창신동 328-18     서울특별시 종로구 지봉로 19,
2      서울특별시 종로구 통인동 147-4번지   서울특별시 종로구 자하문로 35-6
3        서울특별시 종로구 창신동 578-1      서울특별시 종로구 창신길 22
4       서울특별시 종로구 관훈동 197-28    서울특별시 종로구 인사동7길 12
...                      ...                   ...
3896   서울특별시 강동구 천호동 410-105     서울특별시 강동구 진황도로 18
3911  서울특별시 강동구 암사동 421-23번지  서울특별시 강동구 구천면로 371-5
3912  서울특별시 강동구 암사동 514-55번지    서울특별시 강동구 상암로4길 52
3941     서울특별시 강동구 성내동 549-4      서울특별시 강동구 성내로 52
3949  서울특별시 강동구 성내동 127-25번지    서울특별시 강동구 천호옛8길 11

[1207 rows x 2 columns]

In [341]:
### 주소 뒤에 ',' 있는 값들 ',' 기준으로 뒤에 제거 + ',' 제거
# ',' 뒤의 정보 제거 + 공백 제거까지 포함
data['소재지전체주소'] = data['소재지전체주소'].str.split(',').str.get(0).str.strip()
data['도로명전체주소'] = data['도로명전체주소'].str.split(',').str.get(0).str.strip()

data[['소재지전체주소', '도로명전체주소']]

                     소재지전체주소               도로명전체주소
0      서울특별시 종로구 원남동 49-17번지     서울특별시 종로구 율곡로 180
1       서울특별시 종로구 창신동 328-18      서울특별시 종로구 지봉로 19
2      서울특별시 종로구 통인동 147-4번지   서울특별시 종로구 자하문로 35-6
3        서울특별시 종로구 창신동 578-1      서울특별시 종로구 창신길 22
4       서울특별시 종로구 관훈동 197-28    서울특별시 종로구 인사동7길 12
...                      ...                   ...
3896   서울특별시 강동구 천호동 410-105     서울특별시 강동구 진황도로 18
3911  서울특별시 강동구 암사동 421-23번지  서울특별시 강동구 구천면로 371-5
3912  서울특별시 강동구 암사동 514-55번지    서울특별시 강동구 상암로4길 52
3941     서울특별시 강동구 성내동 549-4      서울특별시 강동구 성내로 52
3949  서울특별시 강동구 성내동 127-25번지    서울특별시 강동구 천호옛8길 11

[1207 rows x 2 columns]

In [342]:
### 행정동 추출 위해 ###

# 필수 라이브러리 import 및 기본 상수/엔드포인트 설정
# 주소 문자열 전처리 함수
# 외부 API(행안부/카카오) 호출 래퍼에 간단한 캐시 적용

import re, time, threading, requests, pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed

# API 키
JUSO_KEY  = "devU01TX0FVVEgyMDI1MDgxMjE3MjIzMjExNjA2MjU=" # 도로표준화 때 사용 
KAKAO_KEY = "d86a315467c1c7369d876fd654b23cd0" # 행정동 추출할때 사용

# 엔드포인트 및 공통 HTTP 헤더
JUSO_URL   = "https://www.juso.go.kr/addrlink/addrLinkApi.do"  # 행안부 주소 표준화 API 
ADDR_URL   = "https://dapi.kakao.com/v2/local/search/address.json"  # 카카오 주소→좌표
REGION_URL = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"  # 카카오 좌표→행정/법정동
HEADERS    = {"Authorization": f"KakaoAK {KAKAO_KEY}"}  # 카카오 인증 헤더

# 동시성 & 타임아웃
CONC_JUSO  = 12     # 행안부는 10~15 권장
CONC_KAKAO = 25     # 카카오는 20~30 권장
TIMEOUT = 7         # 각 요청의 타임아웃(초)
MAX_RETRY = 3       # 네트워크 오류 시 재시도 횟수(총 시도 = MAX_RETRY+1)
MAX_SHRINK = 12     # 뒤에서 1글자씩 줄이는 최대 시도 횟수 

## 문자열 가공
def norm_addr(s: str):
    """
    주소 문자열의 기본 정규화:
    - 입력이 문자열이 아니면 None 반환
    - 양 끝 공백 제거, 중복 공백을 단일 공백으로 축소
    - 결과가 빈 문자열이면 None
    """
    if not isinstance(s, str): return None
    s = re.sub(r"\s+", " ", s.strip())
    return s if s else None

def remove_trailing_bunji(s: str):
    """
    주소 문자열 끝이 정확히 '번지'로 끝나는 경우 그 부분만 제거
    - 카카오/행안부에서 '번지' 유무에 따라 매칭 실패하는 경우가 있어 후보 다양화 목적
    """
    if not isinstance(s, str): return None
    s = s.strip()
    return s[:-2].strip() if s.endswith("번지") else s

def cut_before_last_dash(s: str):
    """
    마지막 '-' 앞까지만 남김 (예: '67-138'→'67', '257-48번지'→'257번지')
    - 너무 세밀한 부번/호수 등은 제거하여 매칭률을 높이려는 전략
    """
    if not isinstance(s, str): return None
    m = re.search(r"^(.*?)(?:-\d+)(?:번지)?\s*$", s)
    return m.group(1).strip() if m else s

def progressive_shrink(s: str, max_try=MAX_SHRINK):
    """
    뒤에서 1글자씩 줄여가며 후보 생성 (너무 짧아지지 않게 컷오프)
    - 지나치게 짧아지는 것을 방지하기 위해 최소 길이(min_len) 설정
    - 경험적으로 '...구' 지점까지는 남기는 것이 지역 매칭에 유리해 컷오프에 반영
    """
    s0 = norm_addr(s)
    if not s0: return []
    # '구'의 위치를 찾고, 없으면 -1 → +1로 0이 됨; 최소 8자 보장
    min_len = max(8, s0.find("구")+1)  # '...구'까지는 남기자(대략적인 컷오프)
    out, cur = [], s0
    for _ in range(max_try):
        if len(cur) <= min_len: break
        cur = cur[:-1].rstrip()
        out.append(cur)
    return out

## 행안부 표준화 호출
std_cache, std_lock = {}, threading.Lock() # 같은 입력에 대한 중복 API 호출을 피하기 위해 스레드 세이프 캐시 사용
def juso_standardize(addr: str):
    """
    주소(지번/도로명 무관) -> 표준 도로명주소 or None 
    - 내부 캐시(std_cache)로 동일 주소 반복 호출 방지
    - 네트워크 오류 등 발생 시 재시도 (MAX_RETRY 기준)
    """
    
    if not addr: return addr, None
    a = norm_addr(addr)
    if not a: return addr, None
    with std_lock:
        if a in std_cache: return a, std_cache[a]
    params = {'confmKey': JUSO_KEY, 'currentPage':1, 'countPerPage':1,
              'keyword': a, 'resultType':'json'}
    out = None

    # 재시도 루프 (최대 MAX_RETRY+1회)
    for attempt in range(1, MAX_RETRY+2):
        try:
            r = requests.get(JUSO_URL, params=params, timeout=TIMEOUT); r.raise_for_status()
            j = r.json().get('results',{}).get('juso',[])
            out = j[0].get('roadAddr') if j else None # 최상위 후보 1건만 사용
            break
        except Exception:
            # 마지막 시도가 아니면 지수적 대기 후 재시도
            if attempt == MAX_RETRY+1: out = None
            else: time.sleep(0.5*attempt)
    
    # 캐시에 저장
    with std_lock:
        std_cache[a] = out
    return a, out

In [343]:
### 표준도로명주소 생성
# 후보 주소 생성(정규화, ‘번지’ 제거, 하이픈 절단, 점진 축약) → 행안부 API 병렬 호출 → 첫 성공값으로 표준도로명주소 채움.

def candidate_sequence(row):
    # 원본 정규화 + '번지' 제거
    raw_road = remove_trailing_bunji(norm_addr(row.get('도로명전체주소')))
    raw_lot  = remove_trailing_bunji(norm_addr(row.get('소재지전체주소')))

    cand = []
    # 도로명 → 소재지 (둘 다 사용)
    for a in [raw_road, raw_lot]:
        if a and a not in cand: cand.append(a)

    # 소재지에서 마지막 '-' 앞까지만
    if raw_lot:
        cut = cut_before_last_dash(raw_lot)
        if cut and cut not in cand and cut != raw_lot:
            cand.append(cut)
        # 소재지 주소 뒤에서 1글자씩 줄이기
        for shr in progressive_shrink(raw_lot):
            if shr not in cand: cand.append(shr)

    return cand

# 표준도로명주소 컬럼 준비 (없으면 생성)
if '표준도로명주소' not in data.columns:
    data['표준도로명주소'] = None

# 표준주소가 비어 있는 행들만 대상 선정
need = data['표준도로명주소'].isna()

# 각 행별 후보열 시퀀스 생성
cseq = data.loc[need].apply(candidate_sequence, axis=1)

# 모든 후보 flatten → 유니크 : 후보 리스트를 평탄화(flatten) 후, 순서를 유지한 중복제거(dict.fromkeys 이용)
all_candidates = []
for lst in cseq: all_candidates.extend(lst)
uniq_candidates = list(dict.fromkeys([a for a in all_candidates if a]))  # 순서유지 dedupe
print("유니크 후보 수:", len(uniq_candidates))

# 병렬 표준화 호출 (후보별 1회)
t0 = time.time()
with ThreadPoolExecutor(max_workers=CONC_JUSO) as ex:
    futures = [ex.submit(juso_standardize, a) for a in uniq_candidates]
    for i, f in enumerate(as_completed(futures), 1):
        if i % 200 == 0 or i == len(futures):
            dt = time.time()-t0
            print(f"[JUSO 호출] {i}/{len(futures)} | {i/max(dt,1):.1f} req/s")

# 행별로 첫 성공값 채워넣기
filled_idx = []
for idx, lst in cseq.items():
    std = None
    for a in lst:
        key = norm_addr(a)
        std = std_cache.get(key) # 캐시에 저장된 표준주소 결과 조회
        if std: break
    if std:
        data.at[idx, '표준도로명주소'] = std
        filled_idx.append(idx)

print(f"이번 라운드 채워짐: {len(filled_idx)}")
print("표준도로명주소 결측:", int(data['표준도로명주소'].isna().sum()), "/", len(data))

유니크 후보 수: 6724
[JUSO 호출] 200/6724 | 85.7 req/s
[JUSO 호출] 400/6724 | 84.9 req/s
[JUSO 호출] 600/6724 | 85.0 req/s
[JUSO 호출] 800/6724 | 86.2 req/s
[JUSO 호출] 1000/6724 | 87.4 req/s
[JUSO 호출] 1200/6724 | 88.4 req/s
[JUSO 호출] 1400/6724 | 88.6 req/s
[JUSO 호출] 1600/6724 | 88.7 req/s
[JUSO 호출] 1800/6724 | 88.4 req/s
[JUSO 호출] 2000/6724 | 88.6 req/s
[JUSO 호출] 2200/6724 | 88.6 req/s
[JUSO 호출] 2400/6724 | 88.6 req/s
[JUSO 호출] 2600/6724 | 89.0 req/s
[JUSO 호출] 2800/6724 | 89.1 req/s
[JUSO 호출] 3000/6724 | 89.2 req/s
[JUSO 호출] 3200/6724 | 89.1 req/s
[JUSO 호출] 3400/6724 | 89.2 req/s
[JUSO 호출] 3600/6724 | 89.3 req/s
[JUSO 호출] 3800/6724 | 89.3 req/s
[JUSO 호출] 4000/6724 | 89.3 req/s
[JUSO 호출] 4200/6724 | 89.3 req/s
[JUSO 호출] 4400/6724 | 89.4 req/s
[JUSO 호출] 4600/6724 | 89.4 req/s
[JUSO 호출] 4800/6724 | 89.5 req/s
[JUSO 호출] 5000/6724 | 89.6 req/s
[JUSO 호출] 5200/6724 | 89.8 req/s
[JUSO 호출] 5400/6724 | 89.9 req/s
[JUSO 호출] 5600/6724 | 89.8 req/s
[JUSO 호출] 5800/6724 | 89.8 req/s
[JUSO 호출] 6000/6724 | 89.8 req/s
[JUSO 호출] 6200/6724 | 89.7 req/s
[JUSO 호출] 6400/6724 | 89.7 req/s
[JUSO 호출] 6600/6724 | 89.6 req/s
[JUSO 호출] 6724/6724 | 89.7 req/s
이번 라운드 채워짐: 1207
표준도로명주소 결측: 0 / 1207

In [344]:
### 좌표(WGS84) 채우기 → 행정동
# 기존 좌표 (있으면) 5174→WGS84 변환, (없으면) 카카오 주소검색으로 좌표 보강 → 좌표로 행정동/법정동 역지오코딩(캐시+병렬).
# 좌표 있으면 변환 사용
X_COL, Y_COL = '좌표정보x(epsg5174)', '좌표정보y(epsg5174)'
if X_COL not in data.columns: data[X_COL] = None
if Y_COL not in data.columns: data[Y_COL] = None

def try_import_pyproj():
    """
    pyproj(좌표계 변환 라이브러리) 사용 가능 여부 확인.
    - 사용할 수 있으면 5174 → 4326(WGS84) 변환 Transformer 반환
    - 설치/환경 문제 시 None 반환하여 후속 로직이 안전하게 건너뛰도록 함
    """
    try:
        from pyproj import Transformer
        return Transformer.from_crs(5174, 4326, always_xy=True)
    except Exception:
        return None

_transformer = try_import_pyproj()

def tm5174_to_wgs84(x, y):
    """
    EPSG:5174 (TM중부원점) 좌표를 WGS84 경위도(lon, lat)로 변환.
    - 변환기(_transformer)가 없거나 입력이 결측이면 (None, None) 반환
    - 예외 발생 시에도 (None, None)으로 안전하게 처리
    """
    if pd.isna(x) or pd.isna(y) or _transformer is None: return (None, None)
    try:
        lon, lat = _transformer.transform(float(x), float(y))
        return (lon, lat)
    except Exception:
        return (None, None)

# 기존 좌표 → 경위도 변환 적용
xy0 = data[[X_COL, Y_COL]].apply(lambda r: tm5174_to_wgs84(r[X_COL], r[Y_COL]), axis=1)
data['lon'] = [p[0] for p in xy0]
data['lat'] = [p[1] for p in xy0]
print("기존좌표 변환 후 결측(lon/lat):", int((data['lon'].isna()|data['lat'].isna()).sum()))

# 좌표 없는 행만 카카오 주소검색(표준도로명주소로)
addr_cache, addr_lock = {}, threading.Lock()
def kakao_geocode(addr: str):
    """
    카카오 주소검색 API로 주소 → (x=lon, y=lat) 좌표를 획득
    - 내부 캐시(addr_cache)와 락으로 중복호출/경쟁상황 방지
    - 재시도 및 backoff 적용
    """
    if not isinstance(addr, str) or not addr.strip(): return (None, None)
    a = norm_addr(addr)
    with addr_lock:
        if a in addr_cache: return addr_cache[a]
    out = (None, None)
    for attempt in range(1, MAX_RETRY+2):
        try:
            r = requests.get(ADDR_URL, headers=HEADERS, params={"query": a}, timeout=TIMEOUT)
            r.raise_for_status()
            docs = r.json().get("documents", [])
            out = (float(docs[0]['x']), float(docs[0]['y'])) if docs else (None, None)
            break
        except Exception:
            if attempt == MAX_RETRY+1: out = (None, None)
            else: time.sleep(0.4*attempt)
    with addr_lock:
        addr_cache[a] = out
    return out

# lon/lat 결측인 행만 대상으로 고유 표준주소 목록을 생성하여 병렬 지오코딩
need_geo = data['lon'].isna() | data['lat'].isna()
uniq_std = data.loc[need_geo, '표준도로명주소'].dropna().unique().tolist()

t2 = time.time()
with ThreadPoolExecutor(max_workers=CONC_KAKAO) as ex:
    futures = [ex.submit(kakao_geocode, a) for a in uniq_std]
    for i, f in enumerate(as_completed(futures), 1):
        if i % 200 == 0 or i == len(futures):
            dt = time.time()-t2
            print(f"[카카오 지오코딩] {i}/{len(uniq_std)} | {i/max(dt,1):.1f} req/s")

# 지오코딩 결과를 행 단위로 매핑하여 lon/lat 채우기
data.loc[need_geo, 'lon'] = data.loc[need_geo, '표준도로명주소'].map(
    lambda a: addr_cache.get(norm_addr(a),(None,None))[0]
).astype('float64').values
data.loc[need_geo, 'lat'] = data.loc[need_geo, '표준도로명주소'].map(
    lambda a: addr_cache.get(norm_addr(a),(None,None))[1]
).astype('float64').values
print("최종 좌표 결측:", int((data['lon'].isna() | data['lat'].isna()).sum()))

# 좌표 -> 행정동/법정동
rc_cache, rc_lock = {}, threading.Lock()
def coord2region(lon, lat):
    """
    카카오 coord2regioncode API를 사용해 좌표 → 행정동/법정동 메타데이터를 조회
    - region_type 'H' (행정동), 'B' (법정동) 각각의 3단계 이름 및 코드 반환
    - 네트워크 오류 시 재시도, 그래도 실패하면 None 필드 유지
    """
    if pd.isna(lon) or pd.isna(lat):
        return {"행정동":None,"행정동코드":None,"법정동명":None,"법정동코드":None}
    key = (float(lon), float(lat))
    with rc_lock:
        if key in rc_cache: return rc_cache[key]
    out = {"행정동":None,"행정동코드":None,"법정동명":None,"법정동코드":None}
    for attempt in range(1, MAX_RETRY+2):
        try:
            r = requests.get(REGION_URL, headers=HEADERS, params={"x": key[0], "y": key[1]}, timeout=TIMEOUT)
            r.raise_for_status()
            docs = r.json().get("documents", [])
            h = next((d for d in docs if d.get('region_type')=='H'), None)
            b = next((d for d in docs if d.get('region_type')=='B'), None)
            out = {
                "행정동": (h or {}).get("region_3depth_name"),
                "행정동코드": (h or {}).get("code"),
                "법정동명": (b or {}).get("region_3depth_name"),
                "법정동코드": (b or {}).get("code"),
            }
            break
        except Exception:
            if attempt == MAX_RETRY+1: pass
            else: time.sleep(0.4*attempt)
    with rc_lock:
        rc_cache[key] = out
    return out

# 중복 좌표에 대한 API 호출을 줄이기 위해 고유 (lon, lat) 페어에 대해서만 병렬 조회
pairs = pd.Series(list(zip(data['lon'], data['lat']))).dropna().unique().tolist()
t3 = time.time()
with ThreadPoolExecutor(max_workers=CONC_KAKAO) as ex:
    futures = [ex.submit(coord2region, *p) for p in pairs]
    for i, f in enumerate(as_completed(futures), 1):
        if i % 300 == 0 or i == len(futures):
            dt = time.time()-t3
            print(f"[행정동 조회] {i}/{len(pairs)} | {i/max(dt,1):.1f} req/s")

# 조회 결과를 기존 데이터프레임 순서에 맞춰 병합
tmp = data[['lon','lat']].apply(lambda r: rc_cache.get((r['lon'], r['lat']),
                    {"행정동":None,"행정동코드":None,"법정동명":None,"법정동코드":None}), axis=1)
tmp = pd.json_normalize(tmp)
data[['행정동','행정동코드','법정동명','법정동코드']] = tmp[['행정동','행정동코드','법정동명','법정동코드']].values

print("총 건수:", len(data), " | 행정동 결측:", int(data['행정동'].isna().sum()))
data[['소재지전체주소','도로명전체주소','표준도로명주소','lon','lat','행정동']].head(10)

기존좌표 변환 후 결측(lon/lat): 15
[카카오 지오코딩] 15/15 | 15.0 req/s
최종 좌표 결측: 0
[행정동 조회] 300/1136 | 154.3 req/s
[행정동 조회] 600/1136 | 152.8 req/s
[행정동 조회] 900/1136 | 151.5 req/s
[행정동 조회] 1136/1136 | 125.1 req/s
총 건수: 1207  | 행정동 결측: 0

,소재지전체주소,도로명전체주소,표준도로명주소,lon,lat,행정동
0,서울특별시 종로구 원남동 49-17번지,서울특별시 종로구 율곡로 180,서울특별시 종로구 율곡로 180 (원남동),126.998766,37.575725,종로1.2.3.4가동
1,서울특별시 종로구 창신동 328-18,서울특별시 종로구 지봉로 19,서울특별시 종로구 지봉로 19 (창신동),127.015208,37.571758,창신1동
2,서울특별시 종로구 통인동 147-4번지,서울특별시 종로구 자하문로 35-6,서울특별시 종로구 자하문로 35-6 (통인동),126.970922,37.579146,청운효자동
3,서울특별시 종로구 창신동 578-1,서울특별시 종로구 창신길 22,서울특별시 종로구 창신길 22 (창신동),127.011022,37.572620,창신2동
4,서울특별시 종로구 관훈동 197-28,서울특별시 종로구 인사동7길 12,서울특별시 종로구 인사동7길 12 (관훈동),126.985212,37.573087,종로1.2.3.4가동
5,서울특별시 종로구 숭인동 55-6,서울특별시 종로구 지봉로 82,서울특별시 종로구 지봉로 82 (숭인동),127.015686,37.577449,숭인1동
6,서울특별시 종로구 통인동 35-16,서울특별시 종로구 필운대로6길 3,서울특별시 종로구 필운대로6길 3 (통인동),126.968844,37.580902,청운효자동
7,서울특별시 종로구 삼일대로30길 31,서울특별시 종로구 삼일대로30길 31,서울특별시 종로구 삼일대로30길 31 (익선동),126.989462,37.574417,종로1.2.3.4가동
8,서울특별시 종로구 명륜1가 10-16번지,서울특별시 종로구 명륜길 8,서울특별시 종로구 명륜길 8 (명륜1가),126.996367,37.588129,혜화동
9,서울특별시 종로구 적선동 122-1번지,서울특별시 종로구 새문안로5가길 32,서울특별시 종로구 새문안로5가길 32 (적선동),126.973431,37.574912,사직동

In [345]:
data

,개방서비스명,상세영업상태명,폐업일자,소재지면적,소재지전체주소,도로명전체주소,사업장명,좌표정보x(epsg5174),좌표정보y(epsg5174),욕실수,...,여성종사자수,남성종사자수,다중이용업소여부,표준도로명주소,lon,lat,행정동,행정동코드,법정동명,법정동코드
0,목욕장업,영업,NaT,233.95,서울특별시 종로구 원남동 49-17번지,서울특별시 종로구 율곡로 180,오라카이 대학로 호텔,199821.363678,452603.475535,0.0,...,0.0,0.0,N,서울특별시 종로구 율곡로 180 (원남동),126.998766,37.575725,종로1.2.3.4가동,1111061500,원남동,1111015900
1,목욕장업,영업,NaT,2089.91,서울특별시 종로구 창신동 328-18,서울특별시 종로구 지봉로 19,스파렉스,201273.887782,452163.292543,8.0,...,0.0,0.0,N,서울특별시 종로구 지봉로 19 (창신동),127.015208,37.571758,창신1동,1111067000,창신동,1111017400
2,목욕장업,영업,NaT,262.26,서울특별시 종로구 통인동 147-4번지,서울특별시 종로구 자하문로 35-6,인왕탕,197361.848626,452983.593504,NaN,...,NaN,NaN,N,서울특별시 종로구 자하문로 35-6 (통인동),126.970922,37.579146,청운효자동,1111051500,통인동,1111010800
3,목욕장업,영업,NaT,249.10,서울특별시 종로구 창신동 578-1,서울특별시 종로구 창신길 22,현대옥사우나,200904.097307,452258.945718,0.0,...,0.0,0.0,N,서울특별시 종로구 창신길 22 (창신동),127.011022,37.572620,창신2동,1111068000,창신동,1111017400
4,목욕장업,영업,NaT,1430.00,서울특별시 종로구 관훈동 197-28,서울특별시 종로구 인사동7길 12,백상대중탕,198624.006469,452310.752961,NaN,...,NaN,NaN,N,서울특별시 종로구 인사동7길 12 (관훈동),126.985212,37.573087,종로1.2.3.4가동,1111061500,관훈동,1111012800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,목욕장업,폐업,2020-11-16,1980.00,서울특별시 강동구 천호동 410-105,서울특별시 강동구 진황도로 18,현대비전사우나,211336.172452,448556.794492,2.0,...,NaN,NaN,N,서울특별시 강동구 진황도로 5-1 (천호동),127.129055,37.539196,천호3동,1174062000,천호동,1174010900
3911,목욕장업,폐업,2018-09-27,161.16,서울특별시 강동구 암사동 421-23번지,서울특별시 강동구 구천면로 371-5,상원,212306.755356,449855.853977,2.0,...,NaN,NaN,N,서울특별시 강동구 구천면로 371-5 (암사동),127.140058,37.550888,암사1동,1174057000,암사동,1174010700
3912,목욕장업,폐업,2017-02-23,349.67,서울특별시 강동구 암사동 514-55번지,서울특별시 강동구 상암로4길 52,남양,NaN,NaN,2.0,...,NaN,NaN,N,서울특별시 강동구 암사13길 19 (암사동),127.136971,37.552908,암사1동,1174057000,암사동,1174010700
3941,목욕장업,폐업,2022-06-13,822.98,서울특별시 강동구 성내동 549-4,서울특별시 강동구 성내로 52,퍼시픽,211039.290221,447345.670673,2.0,...,0.0,0.0,N,서울특별시 강동구 성내로 52 (성내동),127.125677,37.528287,성내1동,1174064000,성내동,1174010800
3949,목욕장업,폐업,2019-03-07,198.00,서울특별시 강동구 성내동 127-25번지,서울특별시 강동구 천호옛8길 11,성일목욕탕,210899.162873,447909.072217,6.0,...,0.0,0.0,N,서울특별시 강동구 천호옛8길 11 (성내동),127.124100,37.533365,성내2동,1174065000,성내동,1174010800

In [346]:
data.columns

Index(['개방서비스명', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '도로명전체주소', '사업장명',
       '좌표정보x(epsg5174)', '좌표정보y(epsg5174)', '욕실수', '발한실여부', '여성종사자수',
       '남성종사자수', '다중이용업소여부', '표준도로명주소', 'lon', 'lat', '행정동', '행정동코드', '법정동명',
       '법정동코드'],
      dtype='object')

In [347]:
data[data['행정동'].isna() == 1]

Empty DataFrame
Columns: [개방서비스명, 상세영업상태명, 폐업일자, 소재지면적, 소재지전체주소, 도로명전체주소, 사업장명, 좌표정보x(epsg5174), 좌표정보y(epsg5174), 욕실수, 발한실여부, 여성종사자수, 남성종사자수, 다중이용업소여부, 표준도로명주소, lon, lat, 행정동, 행정동코드, 법정동명, 법정동코드]
Index: []

[0 rows x 21 columns]

In [348]:
data[data['표준도로명주소'].isna() == 1]

Empty DataFrame
Columns: [개방서비스명, 상세영업상태명, 폐업일자, 소재지면적, 소재지전체주소, 도로명전체주소, 사업장명, 좌표정보x(epsg5174), 좌표정보y(epsg5174), 욕실수, 발한실여부, 여성종사자수, 남성종사자수, 다중이용업소여부, 표준도로명주소, lon, lat, 행정동, 행정동코드, 법정동명, 법정동코드]
Index: []

[0 rows x 21 columns]

In [349]:
data.columns

Index(['개방서비스명', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '도로명전체주소', '사업장명',
       '좌표정보x(epsg5174)', '좌표정보y(epsg5174)', '욕실수', '발한실여부', '여성종사자수',
       '남성종사자수', '다중이용업소여부', '표준도로명주소', 'lon', 'lat', '행정동', '행정동코드', '법정동명',
       '법정동코드'],
      dtype='object')

In [350]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1207 entries, 0 to 3949
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           1207 non-null   object
 1   상세영업상태명          1207 non-null   object
 2   폐업일자             542 non-null    datetime64[ns]
 3   소재지면적            1207 non-null   float64
 4   소재지전체주소          1207 non-null   object
 5   도로명전체주소          1207 non-null   object
 6   사업장명             1207 non-null   object
 7   좌표정보x(epsg5174)  1192 non-null   float64
 8   좌표정보y(epsg5174)  1192 non-null   float64
 9   욕실수              1049 non-null   float64
 10  발한실여부            1207 non-null   object
 11  여성종사자수           661 non-null    float64
 12  남성종사자수           661 non-null    float64
 13  다중이용업소여부         1207 non-null   object
 14  표준도로명주소          1207 non-null   object
 15  lon              1207 non-null   float64
 16  lat              1207 non-null   float64
 17  행정동              1207 non-null   object
 18  행정동코드            1207 non-null   object
 19  법정동명             1207 non-null   object
 20  법정동코드            1207 non-null   object
dtypes: datetime64[ns](1), float64(8), object(12)
memory usage: 239.7+ KB

In [351]:
## 일단 행정동 추출까지 된 데이터 저장
data.to_csv('../data/processed/인허가_목욕장업_행정동추출.csv', index=False, encoding='utf-8-sig')

In [352]:
### 행정동 기반 목용장업 데이터에 물재생센터 정보 병합 ###
# 먼저 '행정동' 이름 기준으로 병합 시도 (validate="m:1" 안전장치)
# 만약 매핑에서 H_DNG_NM 중복 때문에 실패하거나 안전하지 않으면,
#    - 중복이지만 처리센터가 모두 동일하면 안전 축약 후 이름 기준 병합
#    - 그게 아니면 "코드 기준 폴백":
#       df: 행정동명 정정(신설/용두→용신, 면목제3.8→면목3.8)
#       df: 행정동코드_trim = 행정동코드 // 100 (뒤 '00' 제거)
#       mapping: 행정동코드는 이미 8자리(trim) → 숫자형 변환만
#       df에서 '용신동'인 행의 행정동코드_trim을 매핑의 용신동 코드로 덮어쓰기
#       df['행정동코드_trim'] ↔ mapping['행정동코드'] 로 left join


df = pd.read_csv('../data/processed/인허가_목욕장업_행정동추출.csv', encoding='utf-8-sig')
mapping_df = pd.read_excel('../data/raw/행정동16년 기준 매핑.xlsx', engine='openpyxl')


# 행정동명 정정
# 신설동, 용두동 -> 용신동
# 면목제3.8동 -> 면목3.8동
name_fix = {'신설동': '용신동', 
            '용두동': '용신동', 
            '면목제3.8동': '면목3.8동'}
df['행정동'] = df['행정동'].replace(name_fix)

# '행정동' 컬럼 기반 병합 우선 시도 
def try_merge_by_name(df_in, map_in):
    """
    H_DNG_NM이 유일하면 이름 기준 병합을 시도하고 결과를 반환.
    유일하지 않다면 None을 반환.
    """
    if map_in['H_DNG_NM'].duplicated().any():
        return None  # 유일하지 않음 → 폴백 필요

    # 병합 (행정동 이름 기준)
    merged_name = df_in.merge(
        map_in[['H_DNG_NM', '처리센터']],
        how='left',
        left_on='행정동',
        right_on='H_DNG_NM',
        validate='m:1'  # 왼쪽 many, 오른쪽 one
    ).rename(columns={'처리센터':'물재생센터'}).drop(columns=['H_DNG_NM'])
    return merged_name

# 일단 시도
merged = try_merge_by_name(df, mapping_df)

# 이름 중복이 있다면: 중복 안전 축약 or 코드 폴백
if merged is None:
    # 중복 진단: 같은 동 이름에 서로 다른 처리센터가 있는지 확인
    g = mapping_df.groupby('H_DNG_NM')['처리센터'].nunique().reset_index(name='센터_고유값_수')
    conflict_keys = g.loc[g['센터_고유값_수'] > 1, 'H_DNG_NM'].tolist()

    if len(conflict_keys) == 0:
        # 처리센터가 실제로는 동일 → 완전 중복(동일 동+센터)이라면 안전 축약 가능
        map_dedup_safe = mapping_df.drop_duplicates(subset=['H_DNG_NM', '처리센터'], keep='first')
        # 여전히 H_DNG_NM 중복이 남는지 확인
        if map_dedup_safe['H_DNG_NM'].duplicated().any():
            # 이론상 거의 없지만, 혹시 남아있으면 코드 폴백으로 전환
            need_fallback = True
        else:
            need_fallback = False
            merged = try_merge_by_name(df, map_dedup_safe)
    else:
        # 같은 동 이름에 처리센터가 서로 다름 → 이름만으론 모호 → 코드 폴백
        need_fallback = True

    # 코드 폴백 (필요한 경우만)
    if merged is None and need_fallback:
        # df 쪽 코드 정규화: 뒤 2자리 제거한 8자리 trim 생성 <- 매핑 데이터의 행정동코드가 이미 8자리로 되어 있기때문에 필요
        df['행정동코드'] = pd.to_numeric(df['행정동코드'], errors='coerce').astype('Int64')
        df['행정동코드_trim'] = (df['행정동코드'] // 100).astype('Int64')

        # mapping 쪽은 이미 8자리 → 숫자형만 보정
        mapping_df['행정동코드'] = pd.to_numeric(mapping_df['행정동코드'], errors='coerce').astype('Int64')

        # 용신동 코드(8자리) 추출
        ys_code = mapping_df.loc[mapping_df['H_DNG_NM'] == '용신동', '행정동코드']
        if ys_code.empty:
            raise ValueError("매핑 파일에서 '용신동'의 행정동코드를 찾지 못했습니다.")
        ys_code = ys_code.iloc[0]

        # df에서 '용신동'으로 정정된 모든 행에 용신동 코드 적용
        df.loc[df['행정동'].eq('용신동'), '행정동코드_trim'] = ys_code

        # 코드 기준 병합
        merged = df.merge(
            mapping_df[['행정동코드', '처리센터']].drop_duplicates(subset=['행정동코드']),
            how='left',
            left_on='행정동코드_trim',
            right_on='행정동코드'
        ).rename(columns={'처리센터':'물재생센터'})

print(f"[요약] 전체 행: {len(merged):,d}")
print(f"[요약] 매핑 성공: {(~merged['물재생센터'].isna()).sum():,d}")
print(f"[요약] 매핑 실패: {merged['물재생센터'].isna().sum():,d}")

merged.to_csv('../data/processed/인허가_목욕장업_물재생센터매핑_결과.csv',
              index=False, encoding='utf-8-sig')
print("[저장 완료] ../data/processed/인허가_목욕장업_물재생센터매핑_결과.csv")

[요약] 전체 행: 1,207
[요약] 매핑 성공: 1,207
[요약] 매핑 실패: 0
[저장 완료] ../data/processed/인허가_목욕장업_물재생센터매핑_결과.csv

In [353]:
merged.columns

Index(['개방서비스명', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '도로명전체주소', '사업장명',
       '좌표정보x(epsg5174)', '좌표정보y(epsg5174)', '욕실수', '발한실여부', '여성종사자수',
       '남성종사자수', '다중이용업소여부', '표준도로명주소', 'lon', 'lat', '행정동', '행정동코드', '법정동명',
       '법정동코드', '물재생센터'],
      dtype='object')

In [354]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207 entries, 0 to 1206
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           1207 non-null   object
 1   상세영업상태명          1207 non-null   object
 2   폐업일자             542 non-null    object
 3   소재지면적            1207 non-null   float64
 4   소재지전체주소          1207 non-null   object
 5   도로명전체주소          1207 non-null   object
 6   사업장명             1207 non-null   object
 7   좌표정보x(epsg5174)  1192 non-null   float64
 8   좌표정보y(epsg5174)  1192 non-null   float64
 9   욕실수              1049 non-null   float64
 10  발한실여부            1207 non-null   object
 11  여성종사자수           661 non-null    float64
 12  남성종사자수           661 non-null    float64
 13  다중이용업소여부         1207 non-null   object
 14  표준도로명주소          1207 non-null   object
 15  lon              1207 non-null   float64
 16  lat              1207 non-null   float64
 17  행정동              1207 non-null   object
 18  행정동코드            1207 non-null   int64
 19  법정동명             1207 non-null   object
 20  법정동코드            1207 non-null   int64
 21  물재생센터            1207 non-null   object
dtypes: float64(8), int64(2), object(12)
memory usage: 207.6+ KB

In [355]:
# 결측은 NaN 유지, 나머지만 int 변환
merged['여성종사자수'] = merged['여성종사자수'].astype('Int64')
merged['남성종사자수'] = merged['남성종사자수'].astype('Int64')
merged['욕실수'] = merged['욕실수'].astype('Int64')

In [356]:
merged['소재지면적'].value_counts() # 0인 값이 4개 있는데 그냥 제거하는게 나을듯함 전체 비율의 0.33% 정도임

소재지면적
660.00    9
198.00    6
264.00    5
0.00      4
330.00    4
         ..
183.00    1
11.50     1
8.50      1
184.80    1
822.98    1
Name: count, Length: 1124, dtype: int64

In [357]:
merged = merged[merged['소재지면적'] != 0] # 소재지면적이 0인값 제거
merged['소재지면적'].value_counts()

소재지면적
660.00    9
198.00    6
264.00    5
330.00    4
825.00    4
         ..
183.00    1
11.50     1
8.50      1
184.80    1
196.56    1
Name: count, Length: 1123, dtype: int64

In [358]:
merged['욕실수'].value_counts() # 0인값이 너무 많음

욕실수
0     417
2     378
1      96
3      35
6      31
4      29
8      17
5      17
10      7
9       5
7       4
12      3
14      2
11      2
16      2
17      1
Name: count, dtype: Int64

In [359]:
missing_bath = merged[merged['욕실수'].isna()]
print("욕실수 결측 행 수:", len(missing_bath))
missing_bath[['폐업일자', '소재지면적', '욕실수', '발한실여부', '표준도로명주소', '물재생센터']].head(10)

욕실수 결측 행 수: 157

   폐업일자    소재지면적   욕실수 발한실여부                             표준도로명주소    물재생센터
2   NaN   262.26  <NA>     N           서울특별시 종로구 자하문로 35-6 (통인동)  중랑물재생센터
4   NaN  1430.00  <NA>     N            서울특별시 종로구 인사동7길 12 (관훈동)  중랑물재생센터
6   NaN   480.00  <NA>     N            서울특별시 종로구 필운대로6길 3 (통인동)  중랑물재생센터
8   NaN   468.27  <NA>     N              서울특별시 종로구 명륜길 8 (명륜1가)  중랑물재생센터
9   NaN   598.44  <NA>     N          서울특별시 종로구 새문안로5가길 32 (적선동)  중랑물재생센터
11  NaN   949.46  <NA>     N  서울특별시 종로구 삼일대로30길 21 (낙원동, 종로오피스텔)  중랑물재생센터
15  NaN   432.00  <NA>     N           서울특별시 종로구 새문안로3길 30 (내수동)  중랑물재생센터
16  NaN   912.97  <NA>     N             서울특별시 종로구 진흥로 432 (구기동)  난지물재생센터
17  NaN  1243.48  <NA>     N          서울특별시 종로구 창경궁로 112-7 (인의동)  중랑물재생센터
18  NaN   625.94  <NA>     N    서울특별시 종로구 율곡로6길 36 (운니동, 오피스텔월드)  중랑물재생센터

In [360]:
merged['여성종사자수'].value_counts() # 0인값이 너무 많음

여성종사자수
0     635
1       9
2       8
4       3
20      2
5       2
10      1
11      1
Name: count, dtype: Int64

In [361]:
### '욕실수','여성종사자수', '남성종사자수' 컬럼 제거 : 결측치 채울 수 없음
merged = merged.drop(['욕실수','여성종사자수', '남성종사자수'], axis=1)
merged.columns

Index(['개방서비스명', '상세영업상태명', '폐업일자', '소재지면적', '소재지전체주소', '도로명전체주소', '사업장명',
       '좌표정보x(epsg5174)', '좌표정보y(epsg5174)', '발한실여부', '다중이용업소여부', '표준도로명주소',
       'lon', 'lat', '행정동', '행정동코드', '법정동명', '법정동코드', '물재생센터'],
      dtype='object')

In [362]:
### 전처리에 사용하였으나, 더이상 필요없는 컬럼 제거
merged = merged.drop(['상세영업상태명', '소재지전체주소', '도로명전체주소', '사업장명',
       '좌표정보x(epsg5174)', '좌표정보y(epsg5174)','표준도로명주소',
       'lon', 'lat', '행정동', '행정동코드', '법정동명', '법정동코드'], axis=1)

merged

     개방서비스명        폐업일자    소재지면적 발한실여부 다중이용업소여부    물재생센터
0      목욕장업         NaN   233.95     N        N  중랑물재생센터
1      목욕장업         NaN  2089.91     Y        N  중랑물재생센터
2      목욕장업         NaN   262.26     N        N  중랑물재생센터
3      목욕장업         NaN   249.10     N        N  중랑물재생센터
4      목욕장업         NaN  1430.00     N        N  중랑물재생센터
...     ...         ...      ...   ...      ...      ...
1202   목욕장업  2020-11-16  1980.00     Y        N  탄천물재생센터
1203   목욕장업  2018-09-27   161.16     Y        N  탄천물재생센터
1204   목욕장업  2017-02-23   349.67     Y        N  탄천물재생센터
1205   목욕장업  2022-06-13   822.98     Y        N  탄천물재생센터
1206   목욕장업  2019-03-07   198.00     N        N  탄천물재생센터

[1203 rows x 6 columns]

In [ ]:
merged.to_csv('../data/processed/인허가_목욕장업_일자별정리_준비.csv', encoding='utf-8-sig', index=False)

In [375]:
src_path = "../data/processed/인허가_목욕장업_일자별정리_준비.csv"
df = pd.read_csv(src_path, encoding="utf-8-sig")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1203 entries, 0 to 1202
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방서비스명    1203 non-null   object
 1   폐업일자      540 non-null    object
 2   소재지면적     1203 non-null   float64
 3   발한실여부     1203 non-null   object
 4   다중이용업소여부  1203 non-null   object
 5   물재생센터     1203 non-null   object
dtypes: float64(1), object(5)
memory usage: 56.5+ KB

In [376]:
# 2017-01-01 ~ 2025-06-30 기간에 대해 물재생센터 4개 × 매일 1행으로 구성된 일자별 데이터
"""
2017-01-01 ~ 2025-06-30 기간에 대해
물재생센터 4개 x 매일 1행이 존재하는 일자별 데이터를 생성

- 개업일자 정보 없음 → 모든 시설은 2017-01-01부터 존재한다고 가정
- 폐업일자 존재 시 → 폐업일 '전날'까지 영업(폐업일 당일은 영업 X)
- 날짜×센터의 모든 조합을 '풀그리드'로 만든 뒤, 누락은 0/기본값으로 채움

입출력
- 입력:  ../data/processed/인허가_목욕장업_일자별정리_준비.csv
- 출력:  ../data/processed/인허가_목욕장업_일자별_물재생센터_영업현황_20170101_20250630.csv
"""

import pandas as pd
import numpy as np
from itertools import product

# 기간 설정
START = pd.Timestamp("2017-01-01")
END = pd.Timestamp("2025-06-30")

# 날짜×센터 풀그리드 생성 시 사용할 '일 단위' 날짜 인덱스
date_index = pd.date_range(START, END, freq="D")

src_path = "../data/processed/인허가_목욕장업_일자별정리_준비.csv"
df = pd.read_csv(src_path, encoding="utf-8-sig")

# 수치형 변환: 면적은 숫자형으로 통일 (문자 → NaN 허용)
df["소재지면적"] = pd.to_numeric(df["소재지면적"], errors="coerce")
# 날짜형 변환: 문자열 → datetime (변환 불가/빈 값은 NaT)
df["폐업일자"] = pd.to_datetime(df["폐업일자"], errors="coerce")

# 물재생센터 목록 추출 (요구사항: 최종적으로 날짜마다 센터 4개 행이 나와야 함)
centers = df["물재생센터"].unique().tolist()

# 영업 기간 계산 : 개업일자 정보가 없으므로 모든 시설이 START부터 존재한다고 가정
df["영업시작일"] = START

# 폐업일자가 있으면 폐업일 전날까지 영업으로 간주
#  - 예: 폐업일=2020-01-10 → 영업종료일_포함 = 2020-01-09
df["영업종료일_포함"] = df["폐업일자"] - pd.Timedelta(days=1)
# 폐업일자 NaT(=미폐업)인 시설은 END까지 영업한다고 간주
df["영업종료일_포함"] = df["영업종료일_포함"].fillna(END)
# 영업 종료일이 분석 종료일을 넘어가면 END로 클리핑
df["영업종료일_포함"] = df["영업종료일_포함"].where(df["영업종료일_포함"] <= END, END)
# 종료일 < 시작일인 레코드는 분석 기간과 겹치지 않으므로 제거
df = df[df["영업종료일_포함"] >= df["영업시작일"]].copy()

# 시설 단위 → 일자 단위 확장 
# 각 시설 레코드마다 [영업시작일, 영업종료일_포함] 구간의 모든 날짜를 생성하여
# 시설 속성(면적, 발한실여부, 다중이용업소여부 등)을 일자별로 복제
def make_daily_rows(row):
    # 시설의 실제 운영 기간과 분석 기간이 겹치는 부분만 날짜 생성
    dts = pd.date_range(max(row["영업시작일"], START),
                        min(row["영업종료일_포함"], END),
                        freq="D")
    if len(dts) == 0:
        # 겹치는 날짜가 전혀 없을 경우 빈 프레임 반환
        return pd.DataFrame(columns=[
            "date", "물재생센터", "개방서비스명",
            "소재지면적", "발한실여부", "다중이용업소여부", "시설_운영"
        ])
    # 운영 중인 기간의 각 날짜별 행 생성
    return pd.DataFrame({
        "date": dts,
        "물재생센터": row["물재생센터"],
        "개방서비스명": row["개방서비스명"],
        "소재지면적": row["소재지면적"],
        "발한실여부": row["발한실여부"],
        "다중이용업소여부": row["다중이용업소여부"],
        # 이후 집계에서 '운영 시설 수'를 계산하기 위해
        "시설_운영": 1
    })

# 모든 시설 레코드에 대해 일자 단위로 확장
daily_list = [make_daily_rows(r) for _, r in df.iterrows()]

# 빈 리스트 방지: concat 전에 조건 처리
fac_daily = (
    pd.concat(daily_list, ignore_index=True)
    if len(daily_list) > 0 else
    pd.DataFrame(columns=[
        "date", "물재생센터", "개방서비스명",
        "소재지면적", "발한실여부", "다중이용업소여부", "시설_운영"
    ])
)

# 날짜×센터 집계
# 동일한 날짜/센터 내에서 여러 시설(행)이 존재할 수 있으므로
#  - 시설수_운영: 해당 일자에 운영 중인 시설 수 (시설_운영 합)
#  - 총소재지면적_운영: 운영 시설들의 면적 합
#  - 발한실_운영: 운영 시설 중 발한실여부 == "Y" 개수
#  - 다중이용_운영: 운영 시설 중 다중이용업소여부 == "Y" 개수
# 이후 시설수_운영 > 0이면 영업여부_센터 = 1, 아니면 0
if not fac_daily.empty:
    grp = fac_daily.groupby(["date", "물재생센터"], as_index=False).agg(
        시설수_운영=("시설_운영", "sum"),
        총소재지면적_운영=("소재지면적", "sum"),
        발한실_운영=("발한실여부", lambda s: (s == "Y").sum()),
        다중이용_운영=("다중이용업소여부", lambda s: (s == "Y").sum()),
    )
    grp["영업여부_센터"] = (grp["시설수_운영"] > 0).astype(int)

    # 개방서비스명
    mode_by_center = (
        fac_daily.groupby("물재생센터")["개방서비스명"]
        .agg(lambda s: s.mode().iat[0] if not s.mode().empty else s.iloc[0])
    )
    grp = grp.merge(mode_by_center.rename("개방서비스명"), on="물재생센터", how="left")
else:
    # 예외 처리 : 확장 결과가 비었을 때의 스키마 유지
    grp = pd.DataFrame(columns=[
        "date", "물재생센터", "시설수_운영", "총소재지면적_운영",
        "발한실_운영", "다중이용_운영", "영업여부_센터", "개방서비스명"
    ])

# 날짜×센터 풀그리드 결합
# 모든 날짜(date_index) × 모든 센터(centers) 조합을 만든 뒤,
# 위 집계(grp)를 LEFT JOIN → 누락된 조합은 0/기본값으로 채움
full_grid = pd.DataFrame(list(product(date_index, centers)), columns=["date", "물재생센터"])
daily_center = full_grid.merge(grp, on=["date", "물재생센터"], how="left")

# 결측치 처리 규칙:
#  - 운영 관련 수치(시설수_운영, 총소재지면적_운영, 발한실_운영, 다중이용_운영, 영업여부_센터) → 0
#  - 개방서비스명 → 센터별/전체 최빈값(없으면 '목욕장업')
default_service = (
    fac_daily["개방서비스명"].mode().iat[0]
    if not fac_daily.empty and not fac_daily["개방서비스명"].mode().empty
    else "목욕장업"
)
for col in ["시설수_운영", "총소재지면적_운영", "발한실_운영", "다중이용_운영", "영업여부_센터"]:
    daily_center[col] = daily_center[col].fillna(0)
daily_center["개방서비스명"] = daily_center["개방서비스명"].fillna(default_service)

# 최종 컬럼 순서로 정리하고, 날짜/센터 기준 오름차순 정렬
daily_center = daily_center[[
    "date", "물재생센터", "개방서비스명",
    "영업여부_센터", "시설수_운영", "총소재지면적_운영",
    "발한실_운영", "다중이용_운영"
]].sort_values(["date", "물재생센터"], ignore_index=True)

out_path = "../data/processed/인허가_목욕장업_일자별_물재생센터_영업현황_20170101_20250630.csv"
daily_center.to_csv(out_path, index=False, encoding="utf-8-sig")

print(f"[저장 완료] {out_path}")
daily_center.head(10)

[저장 완료] ../data/processed/인허가_목욕장업_일자별_물재생센터_영업현황_20170101_20250630.csv

        date    물재생센터 개방서비스명  영업여부_센터  시설수_운영  총소재지면적_운영  발한실_운영  다중이용_운영
0 2017-01-01  난지물재생센터   목욕장업        1     207  139616.41      91        3
1 2017-01-01  서남물재생센터   목욕장업        1     455  630651.35     199       54
2 2017-01-01  중랑물재생센터   목욕장업        1     352  284426.11      85       20
3 2017-01-01  탄천물재생센터   목욕장업        1     189  136330.94      63       19
4 2017-01-02  난지물재생센터   목욕장업        1     207  139616.41      91        3
5 2017-01-02  서남물재생센터   목욕장업        1     455  630651.35     199       54
6 2017-01-02  중랑물재생센터   목욕장업        1     352  284426.11      85       20
7 2017-01-02  탄천물재생센터   목욕장업        1     189  136330.94      63       19
8 2017-01-03  난지물재생센터   목욕장업        1     207  139616.41      91        3
9 2017-01-03  서남물재생센터   목욕장업        1     454  630328.07     199       54

# 목욕장업 인허가 전처리 코드 기반 함수로 모듈화

## 불필요한 공통 컬럼 제거 및 2017이전 폐업일자 제거

In [62]:
data_pool = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_10_35_01_P_수영장업.csv', encoding='cp949')
data_laundry = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_06_20_01_P_세탁업.csv', encoding='cp949')
data_sports = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_10_37_01_P_종합체육시설업.csv', encoding='cp949')
data_gym = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_10_42_01_P_체력단련장업.csv', encoding='cp949')
data_beauty = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_05_18_01_P_미용업.csv', encoding='cp949')
data_hair = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_05_19_01_P_이용업.csv', encoding='cp949')

print(data_pool.columns)
print(data_laundry.columns)
print(data_sports.columns)
print(data_gym.columns)
print(data_beauty.columns)
print(data_hair.columns)

Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', '문화체육업종명', '공사립구분명', '보험가입여부코드', '지도자수', '건축물동수',
       '건축물연면적', '회원모집총인원', '세부업종명', '법인명', 'Unnamed: 37'],
      dtype='object')
Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', '위생업태명', '건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층',
       '사용시작지하층', '사용끝지하층', '조건부허가신고사유', '조건부허가시작일자', '조건부허가종료일자', '건물소유구분명',
       '세탁기수', '여성종사자수', '남성종사자수', '회수건조기수', '다중이용업소여부', 'Unnamed: 44'],
      dtype='object')
Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', 'Unnamed: 28'],
      dtype='object')
Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', '문화체육업종명', '공사립구분명', '보험가입여부코드', '지도자수', '건축물동수',
       '건축물연면적', '휴게실면적', '사무실면적', '탈의실면적', '회원모집총인원', '세부업종명', '법인명',
       'Unnamed: 40'],
      dtype='object')
Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', '위생업태명', '건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층',
       '사용시작지하층', '사용끝지하층', '의자수', '조건부허가신고사유', '조건부허가시작일자', '조건부허가종료일자',
       '건물소유구분명', '여성종사자수', '남성종사자수', '침대수', '다중이용업소여부', 'Unnamed: 44'],
      dtype='object')
Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보x(epsg5174)',
       '좌표정보y(epsg5174)', '위생업태명', '건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층',
       '사용시작지하층', '사용끝지하층', '의자수', '조건부허가신고사유', '조건부허가시작일자', '조건부허가종료일자',
       '건물소유구분명', '여성종사자수', '남성종사자수', '침대수', '다중이용업소여부', 'Unnamed: 44'],
      dtype='object')

/var/folders/6h/wj8wkfqs0jn4r8m61j8bpq_r0000gn/T/ipykernel_41164/1041290051.py:5: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  data_beauty = pd.read_csv('../data/raw/add/6110000_CSV/6110000_서울특별시_05_18_01_P_미용업.csv', encoding='cp949')

In [63]:
'''
# 공통 컬럼 삭제 + 폐업일자(<2017-01-01) 필터 일괄 적용
# 대상: data_pool, data_laundry, data_sports, data_gym, data_beauty, data_hair
import pandas as pd

# 1) 제거할 컬럼 (요청한 목록)
DROP = [
    '번호','개방서비스아이디','개방자치단체코드','관리번호',
    '인허가일자','인허가취소일자',
    '영업상태구분코드','영업상태명','상세영업상태코드',
    '휴업시작일자','휴업종료일자','재개업일자',
    '소재지전화','소재지우편번호','도로명우편번호',
    '최종수정시점','데이터갱신구분','데이터갱신일자',
    '업태구분명','법인명'
]
PROTECT = []  # 꼭 남길 게 있으면 넣기 (예: ['인허가일자','폐업일자'])

def clean_and_filter(df, cutoff='2017-01-01'):
    """공통 컬럼 삭제 + 폐업일자 필터 적용 (짧고 안전하게)."""
    out = df.copy()
    # (A) Unnamed:* 자동 포함해서 삭제 목록 구성
    unnamed = [c for c in out.columns if str(c).strip().startswith('Unnamed:')]
    drop_cols = [c for c in DROP if c in out.columns and c not in PROTECT] + unnamed
    out = out.drop(columns=list(dict.fromkeys(drop_cols)), errors='ignore')
    # (B) 폐업일자 필터: 값이 있고 & 기준 이전이면 삭제
    if '폐업일자' in out.columns:
        s = pd.to_datetime(out['폐업일자'], errors='coerce')
        out = out[(s.isna()) | (s >= pd.Timestamp(cutoff))].reset_index(drop=True)
    return out

# 2) 커널에 있는 대상만 처리 → final_* 변수로 저장
targets = ['data_pool','data_laundry','data_sports','data_gym','data_beauty','data_hair']
for name in targets:
    if name in globals():
        base = name.split('_',1)[-1]
        globals()[f'final_{base}'] = clean_and_filter(globals()[name])

# 3) (선택) 결과 크기만 확인
for var in ['final_pool','final_laundry','final_sports','final_gym','final_beauty','final_hair']:
    if var in globals():
        print(f'{var}:', globals()[var].shape)
'''

'\n# 공통 컬럼 삭제 + 폐업일자(<2017-01-01) 필터 일괄 적용\n# 대상: data_pool, data_laundry, data_sports, data_gym, data_beauty, data_hair\nimport pandas as pd\n\n# 1) 제거할 컬럼 (요청한 목록)\nDROP = [\n    \'번호\',\'개방서비스아이디\',\'개방자치단체코드\',\'관리번호\',\n    \'인허가일자\',\'인허가취소일자\',\n    \'영업상태구분코드\',\'영업상태명\',\'상세영업상태코드\',\n    \'휴업시작일자\',\'휴업종료일자\',\'재개업일자\',\n    \'소재지전화\',\'소재지우편번호\',\'도로명우편번호\',\n    \'최종수정시점\',\'데이터갱신구분\',\'데이터갱신일자\',\n    \'업태구분명\',\'법인명\'\n]\nPROTECT = []  # 꼭 남길 게 있으면 넣기 (예: [\'인허가일자\',\'폐업일자\'])\n\ndef clean_and_filter(df, cutoff=\'2017-01-01\'):\n    """공통 컬럼 삭제 + 폐업일자 필터 적용 (짧고 안전하게)."""\n    out = df.copy()\n    # (A) Unnamed:* 자동 포함해서 삭제 목록 구성\n    unnamed = [c for c in out.columns if str(c).strip().startswith(\'Unnamed:\')]\n    drop_cols = [c for c in DROP if c in out.columns and c not in PROTECT] + unnamed\n    out = out.drop(columns=list(dict.fromkeys(drop_cols)), errors=\'ignore\')\n    # (B) 폐업일자 필터: 값이 있고 & 기준 이전이면 삭제\n    if \'폐업일자\' in out.columns:\n        s = pd.to_datetime(out[\'폐업일자\'], errors=\'coerce\')\n        out = out[(s.isna()) | (s >= pd.Timestamp(cutoff))].reset_index(drop=True)\n    return out\n\n# 2) 커널에 있는 대상만 처리 → final_* 변수로 저장\ntargets = [\'data_pool\',\'data_laundry\',\'data_sports\',\'data_gym\',\'data_beauty\',\'data_hair\']\nfor name in targets:\n    if name in globals():\n        base = name.split(\'_\',1)[-1]\n        globals()[f\'final_{base}\'] = clean_and_filter(globals()[name])\n\n# 3) (선택) 결과 크기만 확인\nfor var in [\'final_pool\',\'final_laundry\',\'final_sports\',\'final_gym\',\'final_beauty\',\'final_hair\']:\n    if var in globals():\n        print(f\'{var}:\', globals()[var].shape)\n'

In [64]:
# =========================================================
# ✅ 공통 컬럼 삭제 + 폐업일자(< 2017-01-01) 필터 일괄 적용 (주석 풍부 버전)
# 대상 변수: data_pool, data_laundry, data_sports, data_gym, data_beauty, data_hair
# - 각 DF에 대해:
#   (1) 불필요 공통 컬럼 삭제 (존재하는 것만 안전하게 drop)
#   (2) '폐업일자'가 있고 & 2017-01-01 이전인 행 제거
# 결과 변수: final_pool, final_laundry, final_sports, final_gym, final_beauty, final_hair
# ---------------------------------------------------------
# ⚠️ '인허가일자'는 아래 DROP 리스트에 포함 → 정말 필요하면 PROTECT에 넣어서 보호하세요.
# =========================================================

import pandas as pd

# (A) 제거 대상 공통 컬럼 목록 — 네가 지정한 컬럼들 반영
DROP = [
    '번호','개방서비스아이디','개방자치단체코드','관리번호',
    '인허가일자','인허가취소일자',
    '영업상태구분코드','영업상태명','상세영업상태코드',
    '휴업시작일자','휴업종료일자','재개업일자',
    '소재지전화','소재지우편번호','도로명우편번호',
    '최종수정시점','데이터갱신구분','데이터갱신일자',
    '업태구분명','법인명'
    # 주의: 파일마다 'Unnamed: 28/37/40/44' 등 임시 컬럼이 달라서
    #       아래에서 'Unnamed:'로 시작하는 컬럼은 자동으로 함께 제거합니다.
]

# (B) 보호 컬럼 — 여기 넣으면 DROP에 있더라도 제거하지 않음
#     (예: 일자 집계가 필요해서 '인허가일자'를 살리고 싶다면 아래처럼 설정)
# PROTECT = ['인허가일자']
PROTECT = []

def clean_and_filter(df: pd.DataFrame, cutoff: str = '2017-01-01') -> pd.DataFrame:
    """
    하나의 DataFrame에 대해 '공통 컬럼 삭제' + '폐업일자 기준 필터'를 적용하여 사본을 반환.
    - df: 원본 DataFrame (원본은 보존)
    - cutoff: 'YYYY-MM-DD' 문자열. 이 날짜 이전의 폐업건은 제거.
    """
    out = df.copy()

    # 1) 삭제할 컬럼 목록 구성 ----------------------------------------
    #    - 사용자가 지정한 DROP 중 실제로 존재하는 컬럼만 선택
    #    - PROTECT에 있는 컬럼은 제거 대상에서 제외
    #    - 'Unnamed:'로 시작하는 임시 컬럼은 모두 자동 포함
    auto_unnamed = [c for c in out.columns if str(c).strip().startswith('Unnamed:')]
    drop_cols = [c for c in DROP if (c in out.columns) and (c not in PROTECT)] + auto_unnamed

    # 중복 제거(순서 유지) 후 안전 drop (없는 컬럼은 무시)
    out = out.drop(columns=list(dict.fromkeys(drop_cols)), errors='ignore')

    # 2) 폐업일자 필터 -----------------------------------------------
    #    - '폐업일자'가 존재하는 경우에만 적용
    #    - 문자열/숫자/빈값 등 다양한 형식이 들어올 수 있으므로 to_datetime(errors='coerce')로 NaT 처리
    #    - "폐업일자 값이 있고" AND "cutoff 이전" → 제거
    if '폐업일자' in out.columns:
        close_series = pd.to_datetime(out['폐업일자'], errors='coerce')   # 잘못된 값은 NaT
        cutoff_ts = pd.Timestamp(cutoff)

        # 제거할 행 마스크: (값이 존재) & (cutoff 이전)
        mask_drop = close_series.notna() & (close_series < cutoff_ts)

        # 실제 제거
        out = out.loc[~mask_drop].reset_index(drop=True)

    return out

# (C) 현재 커널에 올라와 있는 대상들만 자동 처리 --------------------
targets = ['data_pool','data_laundry','data_sports','data_gym','data_beauty','data_hair']

for name in targets:
    if name in globals():
        # 결과 변수명 만들기: data_pool → final_pool
        suffix = name.split('_', 1)[-1]
        out_name = f'final_{suffix}'

        # 처리 + 결과 바인딩
        before_shape = globals()[name].shape
        globals()[out_name] = clean_and_filter(globals()[name], cutoff='2017-01-01')
        after_shape = globals()[out_name].shape

        # 진행 로그: 몇 행 줄었는지 빠르게 확인
        print(f"[{name}] {before_shape} → {after_shape} | 결과: {out_name}")

# (D) (선택) 결과 크기만 한 번 더 요약 출력 -------------------------
for var in ['final_pool','final_laundry','final_sports','final_gym','final_beauty','final_hair']:
    if var in globals():
        print(f"{var}: {globals()[var].shape}")

[data_pool] (247, 38) → (177, 17) | 결과: final_pool
[data_laundry] (15296, 45) → (6328, 25) | 결과: final_laundry
[data_sports] (215, 29) → (150, 9) | 결과: final_sports
[data_gym] (6781, 41) → (5492, 20) | 결과: final_gym
[data_beauty] (95498, 45) → (54399, 25) | 결과: final_beauty
[data_hair] (15428, 45) → (4331, 25) | 결과: final_hair
final_pool: (177, 17)
final_laundry: (6328, 25)
final_sports: (150, 9)
final_gym: (5492, 20)
final_beauty: (54399, 25)
final_hair: (4331, 25)

## 주소처리 모듈화

- 소재지전체주소, 도로명전체주소 -> 표준도로명주소
- 좌표 변환 및 누락 채움
- 좌표 기반 행정동 추출

In [65]:
import re
import time
import threading
import requests
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed

# --- 1. API 설정 및 전역 변수 ---
try:
    from pyproj import Transformer
    _transformer_5174_to_wgs84 = Transformer.from_crs(5174, 4326, always_xy=True)
except ImportError:
    _transformer_5174_to_wgs84 = None
    print("Warning: 'pyproj' library not found. EPSG:5174 coordinate conversion will be skipped.")

JUSO_KEY = "devU01TX0FVVEgyMDI1MDgxMjE3MjIzMjExNjA2MjU="
KAKAO_KEY = "d86a315467c1c7369d876fd654b23cd0"
JUSO_URL = "https://www.juso.go.kr/addrlink/addrLinkApi.do"
ADDR_URL = "https://dapi.kakao.com/v2/local/search/address.json"
REGION_URL = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
HEADERS = {"Authorization": f"KakaoAK {KAKAO_KEY}"}
CONC_JUSO, CONC_KAKAO, TIMEOUT, MAX_RETRY = 12, 25, 10, 5
MAX_SHRINK = 12
_std_cache, _std_lock = {}, threading.Lock()
_addr_cache, _addr_lock = {}, threading.Lock()
_rc_cache, _rc_lock = {}, threading.Lock()


# --- 2. 메인 처리 함수 ---
def process_addresses(df: pd.DataFrame) -> pd.DataFrame:
    data = df.copy()

    # (내부 헬퍼 및 API 호출 함수들은 이전과 동일하게 유지)
    def norm_addr(s: str):
        if not isinstance(s, str): return None
        s = re.sub(r"\s+", " ", s.strip())
        return s if s else None
    def remove_trailing_bunji(s: str):
        s = norm_addr(s)
        return s[:-2].strip() if s and s.endswith("번지") else s
    def cut_before_last_dash(s: str):
        s = norm_addr(s)
        if not s: return None
        m = re.search(r"^(.*?)(?:-\d+)(?:번지)?\s*$", s)
        return m.group(1).strip() if m else s
    def progressive_shrink(s: str, max_try=MAX_SHRINK):
        s0 = norm_addr(s)
        if not s0: return []
        min_len = max(8, s0.find("구") + 1)
        out, cur = [], s0
        for _ in range(max_try):
            if len(cur) <= min_len: break
            cur = cur[:-1].rstrip()
            if cur: out.append(cur)
        return out
    def candidate_sequence(row):
        raw_road = remove_trailing_bunji(row.get('도로명전체주소'))
        raw_lot = remove_trailing_bunji(row.get('소재지전체주소'))
        cand = []
        for a in [raw_road, raw_lot]:
            if a and a not in cand: cand.append(a)
        if raw_lot:
            cut = cut_before_last_dash(raw_lot)
            if cut and cut != raw_lot and cut not in cand: cand.append(cut)
            for shr in progressive_shrink(raw_lot):
                if shr not in cand: cand.append(shr)
        return cand
    def juso_standardize(addr: str):
        a = norm_addr(addr)
        if not a: return
        with _std_lock:
            if a in _std_cache: return
        params = {'confmKey': JUSO_KEY, 'currentPage': 1, 'countPerPage': 1, 'keyword': a, 'resultType': 'json'}
        out = None
        for attempt in range(1, MAX_RETRY + 2):
            try:
                r = requests.get(JUSO_URL, params=params, timeout=TIMEOUT); r.raise_for_status()
                j = r.json().get('results', {}).get('juso', [])
                out = j[0].get('roadAddr') if j else None
                break
            except Exception:
                if attempt > MAX_RETRY: out = None
                else: time.sleep(0.5 * attempt)
        with _std_lock: _std_cache[a] = out
    def kakao_geocode(addr: str):
        a = norm_addr(addr)
        if not a: return
        with _addr_lock:
            if a in _addr_cache: return
        out = (None, None)
        for attempt in range(1, MAX_RETRY + 2):
            try:
                r = requests.get(ADDR_URL, headers=HEADERS, params={"query": a}, timeout=TIMEOUT); r.raise_for_status()
                docs = r.json().get("documents", [])
                out = (float(docs[0]['x']), float(docs[0]['y'])) if docs else (None, None)
                break
            except Exception:
                if attempt > MAX_RETRY: out = (None, None)
                else: time.sleep(0.4 * attempt)
        with _addr_lock: _addr_cache[a] = out
    def coord2region(lon, lat):
        default_out = {"행정동": None, "행정동코드": None, "법정동명": None, "법정동코드": None}
        if pd.isna(lon) or pd.isna(lat): return
        key = (float(lon), float(lat))
        with _rc_lock:
            if key in _rc_cache: return
        out = default_out.copy()
        for attempt in range(1, MAX_RETRY + 2):
            try:
                r = requests.get(REGION_URL, headers=HEADERS, params={"x": key[0], "y": key[1]}, timeout=TIMEOUT); r.raise_for_status()
                docs = r.json().get("documents", [])
                h = next((d for d in docs if d.get('region_type') == 'H'), None)
                b = next((d for d in docs if d.get('region_type') == 'B'), None)
                out = {
                    "행정동": (h or {}).get("region_3depth_name"), "행정동코드": (h or {}).get("code"),
                    "법정동명": (b or {}).get("region_3depth_name"), "법정동코드": (b or {}).get("code"),
                }
                break
            except Exception:
                if attempt > MAX_RETRY: pass
                else: time.sleep(0.4 * attempt)
        with _rc_lock: _rc_cache[key] = out

    # --- 단계 1: 주소 정제 및 상호 보완 ---
    print("--- 1. 주소 정제 시작 ---")
    data['소재지전체주소'] = data['소재지전체주소'].fillna(data['도로명전체주소'])
    data['도로명전체주소'] = data['도로명전체주소'].fillna(data['소재지전체주소'])
    for col in ['소재지전체주소', '도로명전체주소']:
        if col in data and data[col].dtype == 'object':
            data[col] = data[col].str.split().str[:4].str.join(' ').str.split(',').str.get(0).str.strip()

    # --- 단계 2: 표준도로명주소 생성 ---
    print("\n--- 2. 표준도로명주소 생성 시작 ---")
    if '표준도로명주소' not in data.columns: data['표준도로명주소'] = None
    need_std = data[data['표준도로명주소'].isna()]
    if not need_std.empty:
        cseq = need_std.apply(candidate_sequence, axis=1)
        uniq_candidates = list(dict.fromkeys(item for sublist in cseq for item in sublist if item))
        print(f"총 {len(uniq_candidates)}개의 고유 주소 후보로 표준화 API 호출...")
        with ThreadPoolExecutor(max_workers=CONC_JUSO) as ex:
            list(ex.map(juso_standardize, uniq_candidates))
        for idx, lst in cseq.items():
            for a in lst:
                std = _std_cache.get(norm_addr(a))
                if std:
                    data.at[idx, '표준도로명주소'] = std
                    break
    print(f"표준화 완료. 결측 수: {data['표준도로명주소'].isna().sum()}/{len(data)}")

    # --- 단계 3: 좌표 변환 및 보강 ---
    print("\n--- 3. 좌표 변환 및 보강 시작 ---")
    X_COL, Y_COL = '좌표정보x(epsg5174)', '좌표정보y(epsg5174)'
    if X_COL not in data.columns: data[X_COL] = None
    if Y_COL not in data.columns: data[Y_COL] = None
    if 'lon' not in data.columns: data['lon'] = None
    if 'lat' not in data.columns: data['lat'] = None
    if _transformer_5174_to_wgs84:
        valid_tm_coords_idx = data[pd.notna(data[X_COL]) & pd.notna(data[Y_COL])].index
        coords = data.loc[valid_tm_coords_idx].apply(
            lambda r: _transformer_5174_to_wgs84.transform(float(r[X_COL]), float(r[Y_COL])), axis=1)
        if not coords.empty:
            data.loc[coords.index, 'lon'] = [c[0] for c in coords]
            data.loc[coords.index, 'lat'] = [c[1] for c in coords]
    need_geo = data['lon'].isna()
    if need_geo.any():
        uniq_std_to_geo = data.loc[need_geo, '표준도로명주소'].dropna().unique()
        print(f"총 {len(uniq_std_to_geo)}개의 고유 표준주소로 지오코딩 API 호출...")
        with ThreadPoolExecutor(max_workers=CONC_KAKAO) as ex:
            list(ex.map(kakao_geocode, uniq_std_to_geo))
        geo_results = data.loc[need_geo, '표준도로명주소'].map(lambda a: _addr_cache.get(norm_addr(a), (None, None)))
        if not geo_results.empty:
            data.loc[need_geo, 'lon'] = [r[0] for r in geo_results]
            data.loc[need_geo, 'lat'] = [r[1] for r in geo_results]
    print(f"좌표 보강 완료. 최종 좌표 결측 수: {(data['lon'].isna() | data['lat'].isna()).sum()}/{len(data)}")

    # --- 단계 4: 좌표로 행정동 추출 ---
    print("\n--- 4. 행정동 추출 시작 ---")
    valid_coords = data[['lon', 'lat']].dropna().drop_duplicates()
    pairs = list(valid_coords.itertuples(index=False, name=None))
    if pairs:
        print(f"총 {len(pairs)}개의 고유 좌표로 역지오코딩 API 호출...")
        with ThreadPoolExecutor(max_workers=CONC_KAKAO) as ex:
            list(ex.map(lambda p: coord2region(*p), pairs))

    # ★★★ 수정: 최종 병합 방식을 원본과 동일한 .values 방식으로 변경 ★★★
    default_region = {"행정동": None, "행정동코드": None, "법정동명": None, "법정동코드": None}
    tmp = data.apply(lambda r: _rc_cache.get((r['lon'], r['lat']), default_region) if pd.notna(r['lon']) else default_region, axis=1)
    region_df = pd.json_normalize(tmp)
    
    # 생성된 모든 컬럼을 .values를 사용하여 할당
    cols_to_assign = ['행정동', '행정동코드', '법정동명', '법정동코드']
    data[cols_to_assign] = region_df[cols_to_assign].values

    print(f"행정동 추출 완료. 최종 행정동 결측 수: {data['행정동'].isna().sum()}/{len(data)}")
    
    return data

## 행정동 기반 물재생센터 매핑 함수

In [66]:
import pandas as pd

def map_to_center(df: pd.DataFrame, mapping_path: str, save_path: str = None, df_name: str = "인허가_df"):
    """
    df와 매핑 파일을 이용해 '물재생센터'를 병합하는 함수.
    
    Parameters
    ----------
    df : pd.DataFrame
        원본 데이터프레임 (행정동, 행정동코드 포함 필요).
    mapping_path : str
        매핑 엑셀 파일 경로.
    save_path : str, optional
        결과 저장 경로. None이면 저장하지 않음.
    df_name : str, default="인허가_df"
        결과 파일명 prefix.
    
    Returns
    -------
    merged : pd.DataFrame
        매핑 완료된 데이터프레임
    """
    # 매핑 데이터 불러오기
    mapping_df = pd.read_excel(mapping_path, engine='openpyxl')
    
    # 행정동명 정정
    name_fix = {
        '신설동': '용신동', 
        '용두동': '용신동', 
        '면목제3.8동': '면목3.8동'
    }
    df = df.copy()
    df['행정동'] = df['행정동'].replace(name_fix)
    
    # 이름 기준 병합 시도 함수
    def try_merge_by_name(df_in, map_in):
        if map_in['H_DNG_NM'].duplicated().any():
            return None
        merged_name = df_in.merge(
            map_in[['H_DNG_NM', '처리센터']],
            how='left',
            left_on='행정동',
            right_on='H_DNG_NM',
            validate='m:1'
        ).rename(columns={'처리센터':'물재생센터'}).drop(columns=['H_DNG_NM'])
        return merged_name
    
    # 첫 번째 병합 시도
    merged = try_merge_by_name(df, mapping_df)

    if merged is None:
        # 중복 진단
        g = mapping_df.groupby('H_DNG_NM')['처리센터'].nunique().reset_index(name='센터_고유값_수')
        conflict_keys = g.loc[g['센터_고유값_수'] > 1, 'H_DNG_NM'].tolist()

        if len(conflict_keys) == 0:
            map_dedup_safe = mapping_df.drop_duplicates(subset=['H_DNG_NM', '처리센터'], keep='first')
            if map_dedup_safe['H_DNG_NM'].duplicated().any():
                need_fallback = True
            else:
                need_fallback = False
                merged = try_merge_by_name(df, map_dedup_safe)
        else:
            need_fallback = True

        # 코드 기준 폴백
        if merged is None and need_fallback:
            df['행정동코드'] = pd.to_numeric(df['행정동코드'], errors='coerce').astype('Int64')
            df['행정동코드_trim'] = (df['행정동코드'] // 100).astype('Int64')

            mapping_df['행정동코드'] = pd.to_numeric(mapping_df['행정동코드'], errors='coerce').astype('Int64')

            ys_code = mapping_df.loc[mapping_df['H_DNG_NM'] == '용신동', '행정동코드']
            if ys_code.empty:
                raise ValueError("매핑 파일에서 '용신동'의 행정동코드를 찾지 못했습니다.")
            ys_code = ys_code.iloc[0]

            df.loc[df['행정동'].eq('용신동'), '행정동코드_trim'] = ys_code

            merged = df.merge(
                mapping_df[['행정동코드', '처리센터']].drop_duplicates(subset=['행정동코드']),
                how='left',
                left_on='행정동코드_trim',
                right_on='행정동코드'
            ).rename(columns={'처리센터':'물재생센터'})
    
    # 결과 요약 출력
    print(f"[요약] 전체 행: {len(merged):,d}")
    print(f"[요약] 매핑 성공: {(~merged['물재생센터'].isna()).sum():,d}")
    print(f"[요약] 매핑 실패: {merged['물재생센터'].isna().sum():,d}")
    
    # 저장 옵션 처리
    if save_path is not None:
        full_path = f"{save_path}/{df_name}_물재생센터매핑_결과.csv"
        merged.to_csv(full_path, index=False, encoding='utf-8-sig')
        print(f"[저장 완료] {full_path}")
    
    return merged

## 일자별, 물재생센터별 단순 운영숫자 카운트 함수

In [67]:
### 단순하게 물재생센터별로 카운트만 할거라면,,
# %% [markdown]
# # 일자×물재생센터×업종별 일별 카운트 생성 함수 + 파일명에 데이터 태그 포함 (Py 3.8+ 호환)
# - 저장 시 파일명에 인허가 데이터 이름(예: "목욕장업", "수영장업")을 포함하기 위해 `data_tag` 파라미터 추가
# - 예: data_tag="목욕장업" → 인허가_목욕장업_일자별_센터×업종_시설수_20170101_20250630.csv

# %%
import re
import pandas as pd
from itertools import product
from typing import Optional, List  # 3.8+ 호환 타입

def _sanitize_tag(s: str) -> str:
    """
    파일명 안전 문자열로 변환:
    - 양쪽 공백 제거
    - 공백은 '_'로
    - 슬래시 등 위험 문자는 '-'로 치환
    """
    s = s.strip()
    s = s.replace(" ", "_")
    # 파일명에 흔히 문제되는 문자들 제거/치환
    s = re.sub(r"[\\/:*?\"<>|]+", "-", s)
    return s

def build_daily_center_industry_counts(
    df: pd.DataFrame,
    out_path: Optional[str] = None,
    start: str = "2017-01-01",
    end: str = "2025-06-30",
    center_col: str = "물재생센터",
    industry_col: str = "개방서비스명",
    close_col: str = "폐업일자",
    centers_override: Optional[List[str]] = None,     # 예: ["서남","탄천","중랑","난지"]
    industries_override: Optional[List[str]] = None,  # 특정 업종 집합 강제 사용 시 지정
    data_tag: Optional[str] = None,                   # ✅ 파일명에 넣을 인허가 데이터 이름(예: "목욕장업")
    date_tag_fmt: str = "%Y%m%d",                     # 파일명 날짜 포맷
) -> pd.DataFrame:
    """
    지정한 기간 동안 매일 `물재생센터 × 업종`별 운영 시설 수(카운트)를 계산해 반환하고,
    필요 시 CSV로 저장합니다. 저장 파일명에 data_tag(인허가 데이터 이름)를 포함할 수 있습니다.

    Returns
    -------
    pd.DataFrame  # 컬럼: ['date', center_col, '업종', '시설수_운영']
    """
    # -------------------------
    # 1) 기간/그리드 기본 준비
    # -------------------------
    START = pd.Timestamp(start)
    END = pd.Timestamp(end)
    date_index = pd.date_range(START, END, freq="D")

    # -------------------------
    # 2) 컬럼 검사 & 날짜 변환
    # -------------------------
    required = {center_col, industry_col, close_col}
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"입력 데이터에 필요한 컬럼 누락: {missing}")

    df = df.copy()
    df[close_col] = pd.to_datetime(df[close_col], errors="coerce")

    # -----------------------------------------
    # 3) 운영기간 계산 (개업일 정보 없다고 가정)
    # -----------------------------------------
    df["영업시작일"] = START
    df["영업종료일_포함"] = (df[close_col] - pd.Timedelta(days=1)).fillna(END)
    df["영업종료일_포함"] = df["영업종료일_포함"].where(df["영업종료일_포함"] <= END, END)
    df = df[df["영업종료일_포함"] >= df["영업시작일"]].copy()

    # -----------------------------------------
    # 4) 시설 → 일자 확장 (센터/업종 보존)
    # -----------------------------------------
    def make_daily_rows(row: pd.Series) -> pd.DataFrame:
        dts = pd.date_range(max(row["영업시작일"], START),
                            min(row["영업종료일_포함"], END),
                            freq="D")
        if len(dts) == 0:
            return pd.DataFrame(columns=["date", center_col, industry_col, "시설_운영"])
        return pd.DataFrame({
            "date": dts,
            center_col: row[center_col],
            industry_col: row[industry_col],
            "시설_운영": 1,   # 이후 sum = 해당 날짜/센터/업종의 시설 수
        })

    parts = [make_daily_rows(r) for _, r in df.iterrows()]
    fac_daily = (pd.concat(parts, ignore_index=True)
                 if parts else
                 pd.DataFrame(columns=["date", center_col, industry_col, "시설_운영"]))

    # -----------------------------------------
    # 5) 날짜×센터×업종 집계
    # -----------------------------------------
    if fac_daily.empty:
        grp = pd.DataFrame(columns=["date", center_col, industry_col, "시설수_운영"])
    else:
        grp = (fac_daily
               .groupby(["date", center_col, industry_col], as_index=False)
               .agg(시설수_운영=("시설_운영", "sum")))

    # -----------------------------------------
    # 6) 풀그리드 생성(날짜 × 센터 × 업종) 후 병합
    # -----------------------------------------
    centers = (centers_override
               if centers_override is not None
               else sorted(df[center_col].dropna().unique().tolist()))
    industries = (industries_override
                  if industries_override is not None
                  else sorted(df[industry_col].dropna().unique().tolist()))

    full_grid = pd.DataFrame(
        list(product(date_index, centers, industries)),
        columns=["date", center_col, industry_col]
    )
    out_df = full_grid.merge(grp, on=["date", center_col, industry_col], how="left")
    out_df["시설수_운영"] = out_df["시설수_운영"].fillna(0).astype(int)

    # -----------------------------------------
    # 7) 정렬 및 반환(업종 별칭)
    # -----------------------------------------
    out_df = (out_df
              .sort_values(["date", center_col, industry_col], ignore_index=True)
              .rename(columns={industry_col: "업종"}))

    # -----------------------------------------
    # 8) 저장(선택) — 파일명에 data_tag 포함
    # -----------------------------------------
    if out_path is not None:
        start_tag = START.strftime(date_tag_fmt)
        end_tag = END.strftime(date_tag_fmt)
        tag_part = f"{_sanitize_tag(data_tag)}_" if data_tag else ""
        fname = f"인허가_{tag_part}_일자별_물재생센터_운영수_{start_tag}_{end_tag}.csv"
        save_full = f"{out_path.rstrip('/')}/{fname}"
        out_df.to_csv(save_full, index=False, encoding="utf-8-sig")
        print(f"[저장 완료] {save_full}")

    # 요약
    print(
        f"[요약] 행수={len(out_df):,d}, 날짜={out_df['date'].nunique():,d}, "
        f"센터={out_df[center_col].nunique():,d}, 업종={out_df['업종'].nunique():,d}"
    )
    return out_df

# %% [markdown]
# ## 사용 예시
# - 데이터셋이 '목욕장업'이면 data_tag="목욕장업" 같이 넘겨 파일명을 구분합니다.
# - 센터명을 4개로 고정하고 싶으면 centers_override에 표준 라벨을 맞춰 주세요.

# %%
# result = build_daily_center_industry_counts(
#     df=merged_pool,                               # 이미 메모리에 있는 DF 사용
#     out_path="../data/processed",
#     start="2017-01-01",
#     end="2025-06-30",
#     center_col="물재생센터",
#     industry_col="개방서비스명",
#     close_col="폐업일자",
#     centers_override=["서남", "탄천", "중랑", "난지"],
#     industries_override=None,
#     data_tag="목욕장업"                           # ✅ 파일명에 포함될 태그
# )
# result.head()

# 2. 수영장업 인허가 데이터
- 수영장 등 수영 같은 레크레이션을 즐기기 위해 인공적으로 물을 채워 제공하는 업소정보
- 6110000_서울특별시_10_35_01_P_수영장업.csv

In [68]:
pool = process_addresses(final_pool)

--- 1. 주소 정제 시작 ---

--- 2. 표준도로명주소 생성 시작 ---
총 1193개의 고유 주소 후보로 표준화 API 호출...
표준화 완료. 결측 수: 0/177

--- 3. 좌표 변환 및 보강 시작 ---
총 4개의 고유 표준주소로 지오코딩 API 호출...
좌표 보강 완료. 최종 좌표 결측 수: 0/177

--- 4. 행정동 추출 시작 ---
총 170개의 고유 좌표로 역지오코딩 API 호출...
행정동 추출 완료. 최종 행정동 결측 수: 0/177

In [69]:
pool.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           177 non-null    object
 1   상세영업상태명          177 non-null    object
 2   폐업일자             30 non-null     object
 3   소재지면적            0 non-null      float64
 4   소재지전체주소          177 non-null    object
 5   도로명전체주소          177 non-null    object
 6   사업장명             177 non-null    object
 7   좌표정보x(epsg5174)  173 non-null    float64
 8   좌표정보y(epsg5174)  173 non-null    float64
 9   문화체육업종명          177 non-null    object
 10  공사립구분명           177 non-null    object
 11  보험가입여부코드         66 non-null     object
 12  지도자수             115 non-null    float64
 13  건축물동수            75 non-null     float64
 14  건축물연면적           109 non-null    float64
 15  회원모집총인원          64 non-null     float64
 16  세부업종명            0 non-null      float64
 17  표준도로명주소          177 non-null    object
 18  lon              177 non-null    object
 19  lat              177 non-null    object
 20  행정동              177 non-null    object
 21  행정동코드            177 non-null    object
 22  법정동명             177 non-null    object
 23  법정동코드            177 non-null    object
dtypes: float64(8), object(16)
memory usage: 33.3+ KB

In [70]:
## 일단 행정동 추출까지 된 데이터 저장
pool.to_csv('../data/processed/인허가_수영장업_행정동추출.csv', index=False, encoding='utf-8-sig')

In [71]:
merged_pool = map_to_center(pool, '../data/raw/행정동16년 기준 매핑.xlsx', '../data/processed/', '인허가_수영장업')
merged_pool

[요약] 전체 행: 177
[요약] 매핑 성공: 177
[요약] 매핑 실패: 0
[저장 완료] ../data/processed//인허가_수영장업_물재생센터매핑_결과.csv

,개방서비스명,상세영업상태명,폐업일자,소재지면적,소재지전체주소,도로명전체주소,사업장명,좌표정보x(epsg5174),좌표정보y(epsg5174),문화체육업종명,...,회원모집총인원,세부업종명,표준도로명주소,lon,lat,행정동,행정동코드,법정동명,법정동코드,물재생센터
0,수영장업,직권말소,2020-03-13,NaN,서울특별시 종로구 청운동 123번지,서울특별시 종로구 자하문로 105,청운스포츠센터,197224.271407,453711.382152,수영장업,...,NaN,NaN,서울특별시 종로구 자하문로 105 (청운동),126.969361,37.585703,청운효자동,1111051500,청운동,1111010100,중랑물재생센터
1,수영장업,영업중,NaN,NaN,서울특별시 중구 명동1가 1-1,서울특별시 중구 명동1가 1-1,서울YWCA 스포츠센터,198705.527320,451401.164804,수영장업,...,0.0,NaN,서울특별시 중구 명동11길 20 (명동1가),126.986136,37.564891,명동,1114055000,명동1가,1114012600,난지물재생센터
2,수영장업,영업중,NaN,NaN,서울특별시 중구 장충동2가 산,서울특별시 중구 장충동2가 산,Banyan Tree Club&SPA Seoul Oasis,200193.232425,449809.744685,수영장업,...,0.0,NaN,서울특별시 중구 남산공원길 372 (장충동2가),127.002975,37.550554,장충동,1114058000,장충동2가,1114014400,중랑물재생센터
3,수영장업,영업중,NaN,NaN,서울특별시 중구 순화동 2-6번지,서울특별시 중구 순화동 2-6번지,중앙일보교육사업단(중앙문화센터),197395.761334,451285.616478,수영장업,...,NaN,NaN,서울특별시 중구 서소문로 89-31 (순화동),126.971312,37.563847,소공동,1114052000,순화동,1114016800,난지물재생센터
4,수영장업,영업중,NaN,NaN,서울특별시 중구 흥인동 13-1번지,서울특별시 중구 흥인동 13-1번지,뉴)월드스포랜드,201442.039019,451619.845549,수영장업,...,NaN,NaN,서울특별시 중구 다산로46길 17 (흥인동),127.01711,37.566862,신당동,1114061500,흥인동,1114016300,중랑물재생센터
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,수영장업,영업중,NaN,NaN,서울특별시 강동구 상일동 126번지,서울특별시 강동구 구천면로93길 12,한국시각장애인복지재단,214866.322883,449869.026666,수영장업,...,NaN,NaN,서울특별시 강동구 구천면로93길 12 (상일동),127.169024,37.550969,상일1동,1174052500,상일동,1174010300,탄천물재생센터
173,수영장업,영업중,NaN,NaN,서울특별시 강동구 성내동 445-7,서울특별시 강동구 양재대로81길 64,키즈토피아,211510.777132,446882.690090,수영장업,...,200.0,NaN,서울특별시 강동구 양재대로81길 64 (성내동),127.131004,37.52411,성내3동,1174066000,성내동,1174010800,탄천물재생센터
174,수영장업,영업중,NaN,NaN,서울특별시 강동구 명일동 305-39,서울특별시 강동구 양재대로 1665,오션키즈,212643.005289,450239.699709,수영장업,...,0.0,NaN,서울특별시 강동구 양재대로 1665 (명일동),127.14387,37.554342,명일1동,1174053000,명일동,1174010100,탄천물재생센터
175,수영장업,영업중,NaN,NaN,서울특별시 강동구 강일동 679,서울특별시 강동구 아리수로 427,나우수영,215356.343213,451422.369618,수영장업,...,0.0,NaN,서울특별시 강동구 아리수로 427 (강일동),127.174601,37.564957,강일동,1174051500,강일동,1174011000,탄천물재생센터
176,수영장업,영업중,NaN,NaN,서울특별시 강동구 명일동 48-14,서울특별시 강동구 동남로71길 24,아이키즈스윔,213607.407455,449980.645505,수영장업,...,0.0,NaN,서울특별시 강동구 동남로71길 24 (명일동),127.154779,37.551994,명일2동,1174054000,명일동,1174010100,탄천물재생센터

In [72]:
merged_pool.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           177 non-null    object
 1   상세영업상태명          177 non-null    object
 2   폐업일자             30 non-null     object
 3   소재지면적            0 non-null      float64
 4   소재지전체주소          177 non-null    object
 5   도로명전체주소          177 non-null    object
 6   사업장명             177 non-null    object
 7   좌표정보x(epsg5174)  173 non-null    float64
 8   좌표정보y(epsg5174)  173 non-null    float64
 9   문화체육업종명          177 non-null    object
 10  공사립구분명           177 non-null    object
 11  보험가입여부코드         66 non-null     object
 12  지도자수             115 non-null    float64
 13  건축물동수            75 non-null     float64
 14  건축물연면적           109 non-null    float64
 15  회원모집총인원          64 non-null     float64
 16  세부업종명            0 non-null      float64
 17  표준도로명주소          177 non-null    object
 18  lon              177 non-null    object
 19  lat              177 non-null    object
 20  행정동              177 non-null    object
 21  행정동코드            177 non-null    object
 22  법정동명             177 non-null    object
 23  법정동코드            177 non-null    object
 24  물재생센터            177 non-null    object
dtypes: float64(8), object(17)
memory usage: 34.7+ KB

In [85]:
result = build_daily_center_industry_counts(
    df=merged_pool,
    out_path="../data/processed",
    start="2017-01-01",
    end="2025-06-30",
    center_col="물재생센터",
    industry_col="개방서비스명",
    close_col="폐업일자",
    centers_override=None,
    industries_override=None,
    data_tag="수영장업"   
    )
result.head()

[저장 완료] ../data/processed/인허가_수영장업__일자별_물재생센터_운영수_20170101_20250630.csv
[요약] 행수=12,412, 날짜=3,103, 센터=4, 업종=1

        date    물재생센터    업종  시설수_운영
0 2017-01-01  난지물재생센터  수영장업      28
1 2017-01-01  서남물재생센터  수영장업      64
2 2017-01-01  중랑물재생센터  수영장업      46
3 2017-01-01  탄천물재생센터  수영장업      39
4 2017-01-02  난지물재생센터  수영장업      28

# 3. 세탁업 인허가 데이터
- 빨래방, 세탁소, 운동화빨래방 등 의류 기타섬유제품이나 피혁제품등을 세탁하는 업소 정보
- 6110000_서울특별시_06_20_01_P_세탁업.csv
- laundry

In [74]:
laundry = process_addresses(final_laundry)

--- 1. 주소 정제 시작 ---

--- 2. 표준도로명주소 생성 시작 ---
총 26567개의 고유 주소 후보로 표준화 API 호출...
표준화 완료. 결측 수: 0/6328

--- 3. 좌표 변환 및 보강 시작 ---
총 69개의 고유 표준주소로 지오코딩 API 호출...
좌표 보강 완료. 최종 좌표 결측 수: 1/6328

--- 4. 행정동 추출 시작 ---
총 5598개의 고유 좌표로 역지오코딩 API 호출...
행정동 추출 완료. 최종 행정동 결측 수: 1/6328

In [75]:
## 일단 행정동 추출까지 된 데이터 저장
laundry.to_csv('../data/processed/인허가_세탁업_행정동추출.csv', index=False, encoding='utf-8-sig')
merged_laundry = map_to_center(laundry, '../data/raw/행정동16년 기준 매핑.xlsx', '../data/processed/', '인허가_수영장업')
merged_laundry

[요약] 전체 행: 6,328
[요약] 매핑 성공: 6,327
[요약] 매핑 실패: 1
[저장 완료] ../data/processed//인허가_수영장업_물재생센터매핑_결과.csv

,개방서비스명,상세영업상태명,폐업일자,소재지면적,소재지전체주소,도로명전체주소,사업장명,좌표정보x(epsg5174),좌표정보y(epsg5174),위생업태명,...,회수건조기수,다중이용업소여부,표준도로명주소,lon,lat,행정동,행정동코드,법정동명,법정동코드,물재생센터
0,세탁업,영업,NaN,33.10,서울특별시 종로구 명륜1가 46-9,서울특별시 종로구 혜화로 11,세담방,199938.394948,453805.179644,빨래방업,...,0.0,N,서울특별시 종로구 혜화로 11 (명륜1가),127.00009,37.586552,혜화동,1111065000,명륜1가,1111017000,중랑물재생센터
1,세탁업,영업,NaN,36.36,서울특별시 종로구 소격동 158-2,서울특별시 종로구 율곡로1길 76,수도사,198306.036168,452931.767617,일반세탁업,...,0.0,N,서울특별시 종로구 율곡로1길 76 (소격동),126.981611,37.578681,삼청동,1111054000,소격동,1111014200,중랑물재생센터
2,세탁업,영업,NaN,40.04,서울특별시 종로구 수송동 58,서울특별시 종로구 삼봉로 81,서울사,198324.653632,452252.812389,일반세탁업,...,0.0,N,서울특별시 종로구 삼봉로 81 (수송동),126.981823,37.572564,종로1.2.3.4가동,1111061500,수송동,1111012400,중랑물재생센터
3,세탁업,영업,NaN,57.95,서울특별시 종로구 신교동 57번지,서울특별시 종로구 자하문로 83,세탁25,197286.715580,453459.221615,일반세탁업,...,0.0,N,서울특별시 종로구 자하문로 83 (신교동),126.970069,37.583431,청운효자동,1111051500,신교동,1111010200,중랑물재생센터
4,세탁업,영업,NaN,32.00,서울특별시 종로구 창신동 703,서울특별시 종로구 낙산길 196,12호우리세탁,200971.425718,453113.875179,일반세탁업,...,0.0,N,서울특별시 종로구 낙산길 196 (창신동),127.011785,37.580323,창신3동,1111069000,창신동,1111017400,중랑물재생센터
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6323,세탁업,폐업,2022-05-18,24.44,서울특별시 강동구 천호동 574,서울특별시 강동구 천중로27길 70,마마운동화세탁,212058.362464,449274.556895,운동화전문세탁업,...,0.0,N,"서울특별시 강동구 천중로27길 70 (천호동, 청운캐슬)",127.137238,37.545654,천호1동,1174060000,천호동,1174010900,탄천물재생센터
6324,세탁업,폐업,2025-02-25,18.75,서울특별시 강동구 명일동 42,서울특별시 강동구 고덕로62길 66,우성세탁소,213354.806800,449887.005648,일반세탁업,...,0.0,N,서울특별시 강동구 고덕로62길 66 (명일동),127.151919,37.551154,명일2동,1174054000,명일동,1174010100,탄천물재생센터
6325,세탁업,폐업,2020-08-31,45.86,서울특별시 강동구 명일동 246-1,서울특별시 강동구 상암로61길 40,크린팩토리 명일점,213430.532624,449586.905358,빨래방업,...,0.0,N,서울특별시 강동구 상암로61길 40 (명일동),127.15277,37.548449,명일2동,1174054000,명일동,1174010100,탄천물재생센터
6326,세탁업,폐업,2023-06-07,32.49,서울특별시 강동구 강일동 76-2,서울특별시 강동구 아리수로93나길 38,미사세탁(고덕강일점),215303.913311,452189.755118,일반세탁업,...,1.0,N,서울특별시 강동구 아리수로93나길 38 (강일동),127.174024,37.571871,강일동,1174051500,강일동,1174011000,탄천물재생센터
6327,세탁업,폐업,2024-01-31,16.70,서울특별시 강동구 상일동 513,서울특별시 강동구 고덕로80길 123,동산수선세탁,214664.448708,449988.903850,일반세탁업,...,0.0,N,서울특별시 강동구 고덕로80길 123 (상일동),127.166742,37.552052,상일1동,1174052500,상일동,1174010300,탄천물재생센터

In [76]:
merged_laundry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           6328 non-null   object
 1   상세영업상태명          6328 non-null   object
 2   폐업일자             2908 non-null   object
 3   소재지면적            6322 non-null   float64
 4   소재지전체주소          6328 non-null   object
 5   도로명전체주소          6328 non-null   object
 6   사업장명             6328 non-null   object
 7   좌표정보x(epsg5174)  6256 non-null   float64
 8   좌표정보y(epsg5174)  6256 non-null   float64
 9   위생업태명            6328 non-null   object
 10  건물지상층수           5119 non-null   float64
 11  건물지하층수           4655 non-null   float64
 12  사용시작지상층          4692 non-null   float64
 13  사용끝지상층           4360 non-null   float64
 14  사용시작지하층          3302 non-null   float64
 15  사용끝지하층           3019 non-null   float64
 16  조건부허가신고사유        6 non-null      object
 17  조건부허가시작일자        3 non-null      float64
 18  조건부허가종료일자        3 non-null      float64
 19  건물소유구분명          1748 non-null   object
 20  세탁기수             4224 non-null   float64
 21  여성종사자수           2663 non-null   float64
 22  남성종사자수           2662 non-null   float64
 23  회수건조기수           4060 non-null   float64
 24  다중이용업소여부         6328 non-null   object
 25  표준도로명주소          6328 non-null   object
 26  lon              6327 non-null   object
 27  lat              6327 non-null   object
 28  행정동              6327 non-null   object
 29  행정동코드            6327 non-null   object
 30  법정동명             6327 non-null   object
 31  법정동코드            6327 non-null   object
 32  물재생센터            6327 non-null   object
dtypes: float64(15), object(18)
memory usage: 1.6+ MB

In [77]:
result = build_daily_center_industry_counts(
    df=merged_laundry,
    out_path="../data/processed",
    start="2017-01-01",
    end="2025-06-30",
    center_col="물재생센터",
    industry_col="개방서비스명",
    close_col="폐업일자",
    centers_override=None,
    industries_override=None,
    data_tag="세탁업"   
    )
result.head()

[저장 완료] ../data/processed/인허가_세탁업__일자별_물재생센터_운영수_20170101_20250630.csv
[요약] 행수=12,412, 날짜=3,103, 센터=4, 업종=1

        date    물재생센터   업종  시설수_운영
0 2017-01-01  난지물재생센터  세탁업     939
1 2017-01-01  서남물재생센터  세탁업    2253
2 2017-01-01  중랑물재생센터  세탁업    2117
3 2017-01-01  탄천물재생센터  세탁업    1018
4 2017-01-02  난지물재생센터  세탁업     939

# 4. 종합체육시설업 인허가 데이터
- 수영, 골프, 체육단련 등과 같은 체육시설을 한 곳에 모아놓은 업소정보
- 6110000_서울특별시_10_37_01_P_종합체육시설업.csv
- sports

In [78]:
sports = process_addresses(final_sports)

--- 1. 주소 정제 시작 ---

--- 2. 표준도로명주소 생성 시작 ---
총 1015개의 고유 주소 후보로 표준화 API 호출...
표준화 완료. 결측 수: 0/150

--- 3. 좌표 변환 및 보강 시작 ---
총 3개의 고유 표준주소로 지오코딩 API 호출...
좌표 보강 완료. 최종 좌표 결측 수: 0/150

--- 4. 행정동 추출 시작 ---
총 143개의 고유 좌표로 역지오코딩 API 호출...
행정동 추출 완료. 최종 행정동 결측 수: 0/150

In [79]:
## 일단 행정동 추출까지 된 데이터 저장
sports.to_csv('../data/processed/인허가_종합체육시설업_행정동추출.csv', index=False, encoding='utf-8-sig')
merged_sports = map_to_center(sports, '../data/raw/행정동16년 기준 매핑.xlsx', '../data/processed/', '인허가_수영장업')
merged_sports

[요약] 전체 행: 150
[요약] 매핑 성공: 150
[요약] 매핑 실패: 0
[저장 완료] ../data/processed//인허가_수영장업_물재생센터매핑_결과.csv

,개방서비스명,상세영업상태명,폐업일자,소재지면적,소재지전체주소,도로명전체주소,사업장명,좌표정보x(epsg5174),좌표정보y(epsg5174),표준도로명주소,lon,lat,행정동,행정동코드,법정동명,법정동코드,물재생센터
0,종합체육시설업,폐업,2021-10-05,NaN,서울특별시 종로구 종로1가 24,서울특별시 종로구 종로 19,르메이에르스포츠 종로센터,198150.300374,452019.212643,서울특별시 종로구 종로 19 (종로1가),126.97985,37.570459,종로1.2.3.4가동,1111061500,종로1가,1111012600,중랑물재생센터
1,종합체육시설업,폐업,2020-06-30,NaN,서울특별시 종로구 원서동 206-4,서울특별시 종로구 창덕궁길 19,현대엔지니어링 주식회사,198924.989608,452899.526099,서울특별시 종로구 창덕궁길 19 (원서동),126.988618,37.578392,가회동,1111060000,원서동,1111014900,중랑물재생센터
2,종합체육시설업,영업중,NaN,NaN,서울특별시 종로구 연지동 136-74번지,서울특별시 종로구 김상옥로 29,서울스포츠클럽,199998.556147,452379.497780,서울특별시 종로구 김상옥로 29 (연지동),127.000771,37.573707,종로5.6가동,1111063000,연지동,1111016000,중랑물재생센터
3,종합체육시설업,영업중,NaN,NaN,서울특별시 종로구 구기동 105-1,서울특별시 종로구 진흥로 446,로제우스,196196.102281,456120.471852,서울특별시 종로구 진흥로 446 (구기동),126.957708,37.607404,평창동,1111056000,구기동,1111018200,난지물재생센터
4,종합체육시설업,영업중,NaN,NaN,서울특별시 종로구 종로6가 289-3,서울특별시 종로구 청계천로 279,클럽501,200717.749032,452011.865092,서울특별시 종로구 청계천로 279 (종로6가),127.008912,37.570394,종로5.6가동,1111063000,종로6가,1111016400,중랑물재생센터
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,종합체육시설업,영업중,NaN,NaN,서울특별시 송파구 방이동 88-2번지,서울특별시 송파구 올림픽로 424,올림픽수영장,211073.356030,446095.113429,서울특별시 송파구 올림픽로 424 (방이동),127.126044,37.51702,오륜동,1171056600,방이동,1171011100,탄천물재생센터
146,종합체육시설업,영업중,NaN,NaN,서울특별시 송파구 신천동 29-1,서울특별시 송파구 잠실로 209,소피텔 앰배서더 서울 호텔 앤 서비스드 레지던스,209337.104502,445744.864426,서울특별시 송파구 잠실로 209 (신천동),127.1064,37.513883,잠실6동,1171071000,신천동,1171010200,탄천물재생센터
147,종합체육시설업,폐업,2018-12-27,NaN,서울특별시 강동구 둔촌동 172-2번지,서울특별시 강동구 양재대로84길 33-17,(주)월드스포피아,212017.544442,446859.875436,서울특별시 강동구 양재대로84길 21 (둔촌동),127.136736,37.523898,둔촌1동,1174069000,둔촌동,1174010600,탄천물재생센터
148,종합체육시설업,영업중,NaN,NaN,서울특별시 강동구 고덕동 353-23,서울특별시 강동구 고덕비즈밸리로 51,초이스바이반트,213847.923700,451564.469961,서울특별시 강동구 고덕비즈밸리로 51 (고덕동),127.157531,37.566261,고덕2동,1174056000,고덕동,1174010200,탄천물재생센터
149,종합체육시설업,영업중,NaN,NaN,서울특별시 강동구 성내동 531,서울특별시 강동구 성내로15길 33,(주) 다빈홀딩스 성일스포렉스,211275.576090,447440.867842,서울특별시 강동구 성내로15길 33 (성내동),127.128352,37.529142,성내1동,1174064000,성내동,1174010800,탄천물재생센터

In [80]:
merged_sports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   개방서비스명           150 non-null    object
 1   상세영업상태명          150 non-null    object
 2   폐업일자             32 non-null     object
 3   소재지면적            0 non-null      float64
 4   소재지전체주소          150 non-null    object
 5   도로명전체주소          150 non-null    object
 6   사업장명             150 non-null    object
 7   좌표정보x(epsg5174)  147 non-null    float64
 8   좌표정보y(epsg5174)  147 non-null    float64
 9   표준도로명주소          150 non-null    object
 10  lon              150 non-null    object
 11  lat              150 non-null    object
 12  행정동              150 non-null    object
 13  행정동코드            150 non-null    object
 14  법정동명             150 non-null    object
 15  법정동코드            150 non-null    object
 16  물재생센터            150 non-null    object
dtypes: float64(3), object(14)
memory usage: 20.0+ KB

In [81]:
result = build_daily_center_industry_counts(
    df=merged_sports,
    out_path="../data/processed",
    start="2017-01-01",
    end="2025-06-30",
    center_col="물재생센터",
    industry_col="개방서비스명",
    close_col="폐업일자",
    centers_override=None,
    industries_override=None,
    data_tag="종합체육시설업"   
    )
result.head()

[저장 완료] ../data/processed/인허가_종합체육시설업__일자별_물재생센터_운영수_20170101_20250630.csv
[요약] 행수=12,412, 날짜=3,103, 센터=4, 업종=1

        date    물재생센터       업종  시설수_운영
0 2017-01-01  난지물재생센터  종합체육시설업      26
1 2017-01-01  서남물재생센터  종합체육시설업      48
2 2017-01-01  중랑물재생센터  종합체육시설업      35
3 2017-01-01  탄천물재생센터  종합체육시설업      41
4 2017-01-02  난지물재생센터  종합체육시설업      26

# 5. 체력단련장업 인허가 데이터
- 헬스장과 같은 체격관리 및 근력, 유연성, 지구력 강화 등을 목표로 운동을 할 때 필요한 도구와 기구를 제공하는 업소정보
- 샤워실 보통 포함하기 때문에 확인
- 6110000_서울특별시_10_42_01_P_체력단련장업.csv

In [82]:
gym = process_addresses(final_gym)

--- 1. 주소 정제 시작 ---

--- 2. 표준도로명주소 생성 시작 ---
총 21357개의 고유 주소 후보로 표준화 API 호출...
표준화 완료. 결측 수: 0/5492

--- 3. 좌표 변환 및 보강 시작 ---
총 62개의 고유 표준주소로 지오코딩 API 호출...
좌표 보강 완료. 최종 좌표 결측 수: 0/5492

--- 4. 행정동 추출 시작 ---
총 4762개의 고유 좌표로 역지오코딩 API 호출...
행정동 추출 완료. 최종 행정동 결측 수: 0/5492

In [83]:
## 일단 행정동 추출까지 된 데이터 저장
gym.to_csv('../data/processed/인허가_체력단련장업_행정동추출.csv', index=False, encoding='utf-8-sig')
merged_gym = map_to_center(gym, '../data/raw/행정동16년 기준 매핑.xlsx', '../data/processed/', '인허가_수영장업')
merged_gym

[요약] 전체 행: 5,492
[요약] 매핑 성공: 5,491
[요약] 매핑 실패: 1
[저장 완료] ../data/processed//인허가_수영장업_물재생센터매핑_결과.csv

,개방서비스명,상세영업상태명,폐업일자,소재지면적,소재지전체주소,도로명전체주소,사업장명,좌표정보x(epsg5174),좌표정보y(epsg5174),문화체육업종명,...,회원모집총인원,세부업종명,표준도로명주소,lon,lat,행정동,행정동코드,법정동명,법정동코드,물재생센터
0,체력단련장업,휴업,NaN,288.00,서울특별시 종로구 관철동 45-1번지,서울특별시 종로구 우정국로2길 21,토브짐,198541.720754,451935.633975,체력단련장업,...,0,NaN,서울특별시 종로구 우정국로2길 21 (관철동),126.984281,37.569707,종로1.2.3.4가동,1111061500,관철동,1111013500,중랑물재생센터
1,체력단련장업,폐업,2021-08-04,262.49,서울특별시 종로구 필운동 227,서울특별시 종로구 사직로 97,종로테니스교실,197245.494047,452668.607698,체력단련장업,...,0,NaN,서울특별시 종로구 사직로 97 (필운동),126.969606,37.576308,사직동,1111053000,필운동,1111011300,중랑물재생센터
2,체력단련장업,폐업,2020-10-26,231.00,서울특별시 종로구 관철동 180,서울특별시 종로구 삼일대로17길 51,리썸,198575.614558,451869.596952,체력단련장업,...,0,NaN,서울특별시 종로구 삼일대로17길 51 (관철동),126.984665,37.569112,종로1.2.3.4가동,1111061500,관철동,1111013500,중랑물재생센터
3,체력단련장업,폐업,2020-01-09,NaN,서울특별시 종로구 체부동 32-2번지,서울특별시 종로구 자하문로 21,CA스포츠,197416.928416,452855.092504,체력단련장업,...,0,NaN,서울특별시 종로구 자하문로 21 (체부동),126.971546,37.577988,사직동,1111053000,체부동,1111011200,중랑물재생센터
4,체력단련장업,폐업,2025-07-03,185.35,서울특별시 종로구 공평동 5-1,서울특별시 종로구 우정국로 26,센트로폴리스 피트니스,198493.358664,452139.024771,체력단련장업,...,0,NaN,서울특별시 종로구 우정국로 26 (공평동),126.983733,37.571539,종로1.2.3.4가동,1111061500,공평동,1111012700,중랑물재생센터
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5487,체력단련장업,직권말소,2021-12-15,NaN,서울특별시 강동구 길동 228-1,서울특별시 강동구 천호대로 1193,연합헬스클럽,212616.960060,448087.909554,체력단련장업,...,0,NaN,서울특별시 강동구 천호대로 1193 (길동),127.143538,37.534955,길동,1174068500,길동,1174010500,탄천물재생센터
5488,체력단련장업,직권말소,2021-12-15,NaN,서울특별시 강동구 천호동 453-22,서울특별시 강동구 천호대로157길 22,코스모폴리탄(COSMOPOLITAN),211192.880933,448497.276598,체력단련장업,...,0,NaN,서울특별시 강동구 천호대로157길 22 (천호동),127.127432,37.538661,천호3동,1174062000,천호동,1174010900,탄천물재생센터
5489,체력단련장업,직권말소,2021-12-15,NaN,서울특별시 강동구 고덕동 503-5,서울특별시 강동구 동남로81길 26,훼밀리헬스클럽,213647.551212,450915.612787,체력단련장업,...,0,NaN,서울특별시 강동구 동남로81길 26 (고덕동),127.155251,37.560418,고덕1동,1174055000,고덕동,1174010200,탄천물재생센터
5490,체력단련장업,직권말소,2019-08-08,NaN,서울특별시 강동구 길동 412-12번지,서울특별시 강동구 양재대로 1457,베니스헬스,212215.378259,448196.854660,체력단련장업,...,0,NaN,서울특별시 강동구 양재대로 1457 (길동),127.138997,37.535942,길동,1174068500,길동,1174010500,탄천물재생센터
5491,체력단련장업,직권말소,2021-12-15,NaN,서울특별시 강동구 성내동 62-4,서울특별시 강동구 천호대로 1012,스카이헬스,210921.837350,448409.265712,체력단련장업,...,0,NaN,서울특별시 강동구 천호대로 1012 (성내동),127.124364,37.537872,성내2동,1174065000,성내동,1174010800,탄천물재생센터

In [84]:
result = build_daily_center_industry_counts(
    df=merged_gym,
    out_path="../data/processed",
    start="2017-01-01",
    end="2025-06-30",
    center_col="물재생센터",
    industry_col="개방서비스명",
    close_col="폐업일자",
    centers_override=None,
    industries_override=None,
    data_tag="체력단련장업"   
    )
result.head()

[저장 완료] ../data/processed/인허가_체력단련장업__일자별_물재생센터_운영수_20170101_20250630.csv
[요약] 행수=12,412, 날짜=3,103, 센터=4, 업종=1

        date    물재생센터      업종  시설수_운영
0 2017-01-01  난지물재생센터  체력단련장업     779
1 2017-01-01  서남물재생센터  체력단련장업    2213
2 2017-01-01  중랑물재생센터  체력단련장업    1355
3 2017-01-01  탄천물재생센터  체력단련장업    1144
4 2017-01-02  난지물재생센터  체력단련장업     779

# 6. 미용업, 이용업 인허가 데이터 
- 미용업 : 헤어, 메이크업, 네일아트와 같이 얼굴, 머리, 피부 등을 손질하여 외모를 아름답게 꾸미는 업소정보
- 6110000_서울특별시_05_18_01_P_미용업.csv
- 이용업 : 이발소와 같이 머리 또는 수염을 깎거나 다듬는 등의 방법으로 용모를 단정하게하는 업소정보
- 6110000_서울특별시_05_19_01_P_이용업.csv

In [ ]:
hair = process_addresses(final_hair)
beauty = process_addresses(final_beauty)